### ISSUE TITLE
[demo1][18조] 어린이 영단어 암기 서비스 "외워져라 뾰로롱"

### ISSUE THREAD

**Issue by leesuji2000** [PiLab-CAU/OpenSourceProject-2401#11]
## 데모링크

https://e128-211-117-79-45.ngrok-free.app
데모기간이 끝나 본 링크는 유효하지 않습니다.

### 사용자
- 이 서비스는 어린이를 대상으로 한 영어 단어 암기 서비스 입니다.
- 외워야할 단어장이 있다는 전제하에 연상기억법을 제공함으로써 영어단어를 좀 더 기억에 남기 위한 도움을 주는 서비스입니다.

### 서비스 이용 방법
- 링크를 타고 들어가시면, **단어**와 **뜻**을 입력하는 창이 있습니다. 사용자가 외워야할 **단어**와 **뜻**을 입력하시면 됩니다.
  
  <img width="716" alt="Pasted Graphic" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/25ae8a51-033b-4a4f-864f-175898ae7b8b">

- 만일 **입력한 단어**가 DB에 있는 경우, DB에 저장되어 있는 연상기억법을 출력합니다.
- 만일 **입력한 단어**가 DB에 없는 경우, GPT가 입력한 단어와 뜻을 기반으로 연상기억법을 생성해줍니다.
- 아래는 apple 입력 예시입니다.
  
  <img width="814" alt="Pasted Graphic 1" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/fde82946-c50e-4b67-896a-715a68121e0b">
- 연상기억법이 출력된 후에 피드백을 남기실 수 있습니다.

  <img width="540" alt="• Not bad" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/d1558108-5242-46f2-a7fc-383f2609b365">

### 서비스 이용 참고사항
- 어린이를 대상으로 하는 영어단어 서비스이기 때문에, 어린어 영단어를 중심으로 DB를 구성하였습니다. 어린이 영단어에는 띄어쓰기가 필요 없기 때문에, 띄어쓰기가 포함된 입력은 알림을 통해서 제한하였습니다.

  <img width="436" alt="127 0 0 15000 내용" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/4157184f-4c27-40a1-b9b5-0685703132a3">

- 영어입력창과 한글입력창에 목적과 다른 단어를 입력하면 알림을 통하여 제한하였습니다. 아래는 뜻 입력창에 영어를 썼을때의 알림입니다.

  <img width="441" alt="127 0 0 15000 내용" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/5bc45e32-35bc-4cdc-837e-132dbf7e77df">

- 욕설을 적는 경우에는 gpt moderation을 이용하여 연상기억법을 제공하지 않도록 하였습니다.

  <img width="435" alt="Pasted Graphic 5" src="https://github.com/leesuji2000/OpenSourceProject-Team-18/assets/64798587/8e43625d-f5b7-405d-a25f-8125e52da2e4">

### 구현 계획
- 보다 기억하기 쉬운 연상기억법 DB 구축
- 신뢰가능한 moderation
- 영단어 오타에 대한 유사도 검증
- 간혹 영어로 연상기억법이 출력되는 오류 잡기
- 예문 추가 
- 틀린 영어, 단어 뜻 정정 알림

**Comment by Tastypotato245** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/29b29d54-85d8-4f89-9285-f47f1429789c)

너무 단순한 단어는 대답이 Fun하고 Cool하게 나오네요. 그래도 재밌습니다!!

아래는 profile인데,

<img width="769" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/77ba1537-898e-49bc-b96c-e433370a9b00">

나름 잘 설명해주는 것 같아요! 그림 생성이 이번 프로젝트에서는 없는 걸로 알고 있어서 아쉽네요 ㅠㅠ

**Comment by leesuji2000** [comment]
현재 DB에 데이터가 많지가 않아서, GPT가 생성해주는 단어들은 모두 DB에 넣고 있는 상황입니다.
이전에 검색했던 단어를 한번 더 검색해보시면 GPT가 생성한 결과보다 빠르게 DB에 저장된 데이터를 확인하실 수 있습니다.
추후 생성된 데이터에서 신뢰가능한것들만 선별해서 저장해두고 관리할 예정입니다.

**Comment by yjyoo3312** [comment]
<img width="798" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/047a0de6-220b-4ebe-a8e7-64e0a2693267">
Readme에 설명된 방법이 잘 작동하는군요! 좀더 DB에  데이터 들이 더 쌓이면 더 좋은 답변들이 나올 걸로 예상합니다.
(현재 수업 데모에서는 문제 없습니다만, 피드백 포스팅 이후 바로 홈으로 돌아가는 것이 아니고 홈버튼이 따로 있는 이유가 있을까요?)

**Comment by Bowoon1216** [comment]
저는 convolution을 의뢰해봤습니다..!
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/105543811/84861354-4088-4583-a2a2-8b8c7123f451)
두꺼운볼 마음에 듭니다...ㅋㅋㅋ 
다만 왜 두꺼운 볼이 나오게 되었는지 ... 살짝 궁금하긴 합니다.. ㅎㅎ 이유에 대한 내용도 답변에 녹이는 건 어떨까요 ~? 
가끔 사용하러 오겠습니다! 😄

**Comment by leesuji2000** [comment]
피드백 감사합니다. 프롬프트를 바꿔서 생성된 연상기억법의 이유도 출력할 수 있는지 확인해보겠습니다!

**Comment by leesuji2000** [comment]
> <img width="798" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/047a0de6-220b-4ebe-a8e7-64e0a2693267">
> 
> Readme에 설명된 방법이 잘 작동하는군요! 좀더 DB에  데이터 들이 더 쌓이면 더 좋은 답변들이 나올 걸로 예상합니다.
> 
> (현재 수업 데모에서는 문제 없습니다만, 피드백 포스팅 이후 바로 홈으로 돌아가는 것이 아니고 홈버튼이 따로 있는 이유가 있을까요?)

서비스를 이용할때마다 피드백을 적어야 한다면 사용자 입장에서 귀찮을수도 있습니다. (저 또한 어떤 서비스를 이용할때, 피드백 남기라고 하면 무시하고 그냥 서비스를 이용하고 싶거든요🤭) 피드백을 남기지 않고, 또 서비스를 이용하고 싶은 분들을 위해서 홈으로 바로 이동하는 버튼을 만들었습니다.

**Comment by leesuji2000** [comment]
> 저는 convolution을 의뢰해봤습니다..!
> 
> ![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/105543811/84861354-4088-4583-a2a2-8b8c7123f451)
> 
> 두꺼운볼 마음에 듭니다...ㅋㅋㅋ 
> 
> 다만 왜 두꺼운 볼이 나오게 되었는지 ... 살짝 궁금하긴 합니다.. ㅎㅎ 이유에 대한 내용도 답변에 녹이는 건 어떨까요 ~? 
> 
> 가끔 사용하러 오겠습니다! 😄 

피드백 감사합니다. 프롬프트를 바꿔서 생성된 연상기억법의 이유도 출력할 수 있는지 시도해보겠습니다!

**Comment by leesuji2000** [comment]
## 서비스를 통해서 피드백을 주신 것 대한 답글

- 예문도 같이 넣어 달라는 피드백이 있었습니다. 추후 데이터 베이스에 예문도 함께 넣어서 제공하겠습니다.
- 연상기억법을 이해하는데 어려운(할루시네이션) 같은 경우는 계속해서 개선해 나갈 예정입니다.

- 서비스 이용해주셔서 감사합니다 :-)

**Comment by sihumji00** [comment]
![18조 피드백](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74344579/36de9266-5953-46d7-80dd-595c1b6d09bd)

서비스 시간이 걸린다는 설명을 심호흡 3번만 기다려달라는 등 ui 텍스트가 재치있네요! 시스템 속도도 빠르고 좋은 것 같아요! 그런데 사진처럼 영어로 설명이 나오는 경우도 종종 있는 것 같습니다..! 또 (영단어: blue / 뜻: 빨간색) 으로 입력했을 때와 같이 영단어와 뜻이 매치되지 않을 때 해당 입력을 반려하거나 뜻을 제대로 수정해주는 등의 피드백이 있었으면 좋겠습니다!

**Comment by leesuji2000** [comment]
> ![18조 피드백](https://private-user-images.githubusercontent.com/74344579/329141213-36de9266-5953-46d7-80dd-595c1b6d09bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzYwODEsIm5iZiI6MTcxNTIzNTc4MSwicGF0aCI6Ii83NDM0NDU3OS8zMjkxNDEyMTMtMzZkZTkyNjYtNTk1My00NmQ3LTgwZGQtNTk1YzFiNmQwOWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MjMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjMwMTBhYmQyNjkxNjVkMGEwYTQyZTBlYzM5MTFjNzM5YWExNWIyMTA1Nzc5YWJlNmMzN2YyOWI3ODc0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHfRi89LBSU_NLARdY5mDkA8C25YxlJEDHdKA2eSH0k)
> 
> 서비스 시간이 걸린다는 설명을 심호흡 3번만 기다려달라는 등 ui 텍스트가 재치있네요! 시스템 속도도 빠르고 좋은 것 같아요! 그런데 사진처럼 영어로 설명이 나오는 경우도 종종 있는 것 같습니다..! 또 (영단어: blue / 뜻: 빨간색) 으로 입력했을 때와 같이 영단어와 뜻이 매치되지 않을 때 해당 입력을 반려하거나 뜻을 제대로 수정해주는 등의 피드백이 있었으면 좋겠습니다!

피드백 감사합니다! 
영어로 결과가 나오는 것은 어린이들이 이해하기 어렵기 때문에 문제점을 찾아서 바꾸도록 하겠습니다.
또한 영어 단어와 뜻이 맞지 않는 것은 추후 알림을 통해서 "영어 단어의 뜻이 틀렸습니다. 옳바른 뜻은 ~입니다." 이런식으로 알릴 예정입니다. 
감사합니다.

**Comment by Handoni** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/101948889/194f6560-b916-4c5a-aeed-ab7ecdedd569)
실수로 오타를 냈는데, 어.. 어린이용 단어에 ass..가 나와서 깜짝 놀랐습니다. 입력 말고도 출력에도 필터링이 좀 있으면 좋을 것 같습니다!

**Comment by leesuji2000** [comment]
> ![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/101948889/194f6560-b916-4c5a-aeed-ab7ecdedd569)
> 
> 실수로 오타를 냈는데, 어.. 어린이용 단어에 ass..가 나와서 깜짝 놀랐습니다. 입력 말고도 출력에도 필터링이 좀 있으면 좋을 것 같습니다!

흐업..😢 피드백 감사합니다.
출력 단어들도 필터링하도록 하겠습니다.
