### ISSUE TITLE
[demo1][3조] Narae: Your Personal AI Mentor 

### ISSUE THREAD

**Issue by IamGroooooot** [PiLab-CAU/OpenSourceProject-2401#12]
# 데모 링크:
https://app.my-narae.link/

# 사용 설명

Narae의 서비스 이용 방법은 다음과 같습니다.
아래의 예시 사진을 참고 부탁드립니다.

## 1. 랜딩 페이지 접속
- 데모 링크로 접속하면 다음과 같은 메인 페이지를 볼 수 있습니다.
![1](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/eaf6a39f-272a-4bd5-8b27-da6c6af32cca)

## 2. 로그인
- 위 랜딩 페이지에서 `서비스 사용해보기` 버튼을 누르면 로그인 페이지로 리다이렉트 됩니다.
- 이미 가입한 이메일 주소는 로그인, 새로운 이메일 주소는 회원가입으로 진행됩니다. 
![2](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/92c24b9f-2b59-4321-b7af-50f2286f144d)

## 3. 멘토 리스트
- 해당 화면에서 새로운 멘토를 추가하거나, 이미 추가한 멘토를 수정/삭제/대화하기 메뉴로 이동할 수 있습니다.
![3](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/55ad8ed4-74aa-4a6b-95df-558c12bf4f22)

## 4. 멘토 추가하기
- `멘토 리스트` 페이지에서 멘토 추가하기 버튼을 클릭하면 해당 페이지로 이동합니다.
- 해당 페이지에서 멘토 이름, 분야 선택, [STICC](https://brunch.co.kr/@agile-people/44)형식을 기반의 자신의 상황을 효과적으로 전달 할 수 있습니다.
![4](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/446edc84-eac9-4bc0-8ddb-9f51258b19a6)

## 5. 멘토 수정하기
- `멘토 리스트` 페이지에서 `수정` 버튼을 클릭하면 해당 페이지로 이동합니다.
- 해당 페이지에서 기존에 추가한 멘토 정보를 수정할 수 있습니다.
![5](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/86df1d28-346f-4695-b275-1ff12713cb37)
![6](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/42fe5b61-1611-436d-87f4-0a7605e380d0)

## 6. 멘토 삭제하기
- `멘토 리스트` 페이지에서 `삭제` 버튼을 클릭하면 멘토를 삭제합니다.
![9](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/3922b660-8949-471c-8f03-60abb571f1ac)

## 7. 멘토와 대화하기
- `멘토 리스트` 페이지에서 `대화하기` 버튼을 클릭하면 멘토를 삭제합니다.
- 멘토와는 저희가 직접 프롬프팅한 모델입니다. 기본적으로 사용자가 어려워하는 분야를 입력하면 코칭을 해주도록 되어 있으니 활용해보세요. 
  - 답변을 생성하기까지 몇초가 걸릴 수 있습니다.
  - 이전 대화 기록과 전체적인 대화 기록은 모두 저장되지 않기 때문에 유의해주세요!

### 7-1. 대화 시작하는 법
![7](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/2418bfff-f789-47a6-8db8-99b8e6cc2d10)

### 7-2. 대화 나누기
먼저 대화창에 들어오면 채팅방에 멘토 정보창이 출력됩니다.
이후로 궁금하거나 배우고 싶은 것 등을 물어보면 내 상황에 맞게 코칭해줍니다.
 
<img width="1488" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/16e6986c-bffd-42de-9b55-86a0a091f7b2">

다음과 같이 답변이 오는데 시간이 걸릴 수 있으니 참고해주세요 :)
<img width="1496" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/266763f3-af57-4638-91fd-1acda1c2ee52">

## 8. 로그아웃
- 상단 메뉴에서 `계정` 버튼을 클릭하고 `Logout` 버튼을 클릭하여 로그아웃 할 수 있습니다.
![9](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/22471bcf-2560-44d6-aec7-b20acea47931)

# 기타사항
### 채팅 관련

> 현재 채팅은 원하는 것을 공부하기 위해 공부 방향 제시를 잘 해주는지 봐주시면 감사하겠습니다!

시간이 부족해서 아직 방향 설정만 해주는 하나의 응답만할 수 있는 모델만 채팅에 병합했습니다. 저장 기능도 기반 코드는 거의 완성했지만 테스트를 하지 못하여 병합하지 못했습니다. 다음에는 반영하도록 하겠습니다 😄  

저번에 발표 때 언급했듯이 코드를 짜주는 기능은 저희의 메인 기능이 아닙니다. 오히려 코칭에 집중이 되어 있습니다. 그래서 우선적으로 코칭을 해줄 수 있는 모델을 채팅에 넣었습니다.  

이번 데모 이후에 코드를 짜주거나 질의응답하는 모델은 대화 기록의 Context를 유지하도록 계속 추적되도록 구현될 예정입니다. 사용자 데이터를 저장하는 것도 이때 병합할 예정입니다. 이용에 참고해주세요.   

### 개발중인 기능

- 오늘도 성장하기 위한 실제로 수행할 수 있는 Action 설정하기
- Action을 AI와 대화하면 설정하기
- 대화 추적 기능
- 멘토와의 QnA 기능 (`현재는 학습 방향만 추천하도록 되어 있습니다.`)
- 악의적인 접근을 막기 위한 Moderation 기능
- 피드백을 반영할 수 있는 창구 만들기
- RAG를 통한 할루시네이션 개선

**Comment by Tastypotato245** [comment]
<img width="1654" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/42164011-09f7-4b6c-a323-3ca5362cb021">

잘 설명해주네요!! 다만


<img width="1640" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/804ab863-7c7e-40ff-865f-2eb613cabfba">

예시 코드를 짜지는 못하는 것 같아요. GPT 4.0이 아니라서 그럴까요?

또, 응답에 개행이 있으면 좋을 것 같습니다. GPT처럼 마크다운 문법으로 이쁘게 보여줄 수 있으면 좋겠지만,, 그게 쉬울지는 잘 모르겠네요. 

고생하셨습니다!!

**Comment by WickedFoxes** [comment]
- 혹시 대화 종료 후 대화내용이 저장되지 않는 것은 아직 개발중인 것일까요? 아니면 의도된 것일까요?
- 공부와 관련 없는 내용도 채팅이 반영해주네요. 이에 대한 적절한 대응이 필요할 것 같습니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/e67a2ae9-29fd-4333-8bf7-08e3a6082fd2)
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/0678231e-23c2-413b-8ed7-6c28d4e2f6a5)
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/bd726237-49c7-42d3-bae6-d520a72420c1)

**Comment by Jeong-In-Lee** [comment]
조언 주신 부분, 팀원들과 상의해보도록 하겠습니다. 감사합니다.

**Comment by IamGroooooot** [comment]
@Tastypotato245 피드백 감사합니다. ㅎㅎ

시간이 부족해서 아직 방향 설정만 해주는 하나의 응답만할 수 있는 모델만 채팅에 병합했습니다. 그래서 원하는 것을 공부하기 위해 공부 방향 제시를 잘 해주는지 봐주시면 감사하겠습니다!

코드를 짜주거나 질의응답하는 모델은 대화 기록의 Context를 유지하도록 계속 추적되도록 구현될 예정입니다. 사용자 데이터를 저장하는 것도 이때 병합할 예정입니다. 

다음에는 개행이나 디자인도 더 직관적으로 개선해보겠습니다 :)

**Comment by euije** [comment]
안녕하세요~ 서비스 인상적이게 잘 보았습니다~
멘토와 상담을 했는데 대화를 나눈 내용이 사라져 조금 당황했네요 ㅜㅜ
빨리 이 기능이 먼저 업데이트 되길 기대합니다 ㅎㅎ

아래는 제 멘토를 소개할게요
<img width="1400" alt="스크린샷 2024-05-08 오후 7 01 52" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12531340/956ea3fe-d31e-47d9-b4bb-9806db0e6b65">

**Comment by yjyoo3312** [comment]
<img width="613" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/39e1e8b3-4bd3-4754-bd4d-1fa662c8ae66">

예상보다 추천을 잘 해주는 군요! 재밌게 잘 테스트 해보았습니다

**Comment by Jeong-In-Lee** [comment]
@euije 사용해주셔서 감사합니다. 대화 추적 기능은 데모 끝나는대로 빠르게 개발하겠습니다.

**Comment by Jeong-In-Lee** [comment]
@yjyoo3312 사용해주셔서 감사합니다. 앞으로의 '나래'도 기대해주세요.

**Comment by Haemulramen** [comment]
안녕하세요
사용해봤는데 서비스 정말 좋은 것 같아요!
그런데 응답이 도중에 끊기는 경우가 있는 것 같습니다 제가 기획 관련 질문으로 입력을 해서 그런 영향도 있을까요...?
![3조 캡처본](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/128495883/24b16d24-d0da-4731-9a1b-60fa9ff221ba)

**Comment by IamGroooooot** [comment]
> 안녕하세요
> 
> 사용해봤는데 서비스 정말 좋은 것 같아요!
> 
> 그런데 응답이 도중에 끊기는 경우가 있는 것 같습니다 제가 기획 관련 질문으로 입력을 해서 그런 영향도 있을까요...?
> 
> ![3조 캡처본](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/128495883/24b16d24-d0da-4731-9a1b-60fa9ff221ba)
> 
> 

안녕하세요 @Haemulramen님. 
사용해주셔서 감사합니다. 

저희가 토큰 길이 제한을 걸고 프롬프트를 통해 그 길이 내로 응답하도록 했는데 확인해보니 기획적인 부분이나 긴 답변을 물으면 짤리는 현상이 보이네요!

조금 더 테스트해보고 프롬프트를 강화해보겠습니다!! 확인 감사합니다.
