### ISSUE TITLE
[demo1][17조] Redo

### ISSUE THREAD

**Issue by dzcoffee** [PiLab-CAU/OpenSourceProject-2401#13]
데모링크 https://web-redo-1ru12mlvuze1ma.sel5.cloudtype.app/
========
**데모 테스트 일정 종료로 서버 중단된 상태입니다**

### 사용 전 참고사항
- 클라우드 서비스를 이용해 24시간 배포중입니다.
- 과도한 다중 접속으로 인해 접속 지연이 발생할 수 있습니다. 조금 후에 다시 시도해주세요.
-  GPT API가 비동기적으로 처리되므로 **동시에 문제를 생성하고 답변을 희망할 시** 평균 소요시간보다 오래 걸릴 수 있습니다.
- **모든 이용자의 메모가 공유됩니다.** 따라서 개인적인 내용 작성은 자제 부탁드립니다. (기능 미구현으로 인함)
- 메모의 길이는 **200자 이내**로 작성 부탁드립니다.
- GPT API가 잘못된 형식으로 문제, 답변등을 반환할 경우, 오류가 발생할 수 있습니다.

# 사용설명
## 1. 로그인/회원가입
![bandicam_2024-05-07_20-13-16-165](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/310a9361-7d93-4bc4-9d6f-73442af5ab33)
- 로그인/회원가입 기능은 현재 미적용 상태입니다.
- 단순한 dummy 값을 ID와 비밀번호 입력 칸에 작성한 후 로그인 버튼을 눌러주세요.

## 2. 메인화면
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/c83f9a61-8d1a-472b-b11e-d938dacd2f46)
- 메인화면에서는 메모 확인, 메모 작성, 퀴즈 풀기, 로그아웃 기능을 사용할 수 있습니다.
- 로그아웃 기능은 현재 미적용 상태로 버튼을 클릭하면 이전 화면으로 돌아가도록 구현되어 있습니다.

## 3. 메모 목록 및 메모 확인
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/b3000e17-9143-4f09-8975-83496b278768)
- 좌측 목록 구역에서 작성한 메모를 확인하고 선택할 수 있습니다.
- 메모를 선택 시 우측에 마크다운 형식으로 작성된 메모를 확인하실 수 있습니다.
- '메모 목록' 버튼을 다시 누르시면 최초의 화면으로 돌아갑니다.

## 4. 메모 작성
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/4e4c4afa-3590-461c-b3d9-52d67c27c0cb)
- 좌측 상단의 메모 생성 버튼을 누르시면 메모를 생성하실 수 있습니다.
- 제목, 카테고리, 메모 내용을 입력하고 '메모 등록' 버튼을 누르시면 메모를 저장하실 수 있습니다.
- 카테고리의 경우 velog와 같이 입력 후 'Enter'를 눌러야 등록됩니다.
- **현재 마크다운 형식이 잘 적용되지 않는 경우가 있습니다**

## 5. 퀴즈 생성
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/3e84d7e9-b5c6-4ca2-91cc-186c04db8f4b)
- '퀴즈 풀기' 버튼을 누르시면 작성하신 메모를 바탕으로 퀴즈를 생성하실 수 있습니다.
- 메모 목록 영역에서 퀴즈를 만드실 메모를 선택하시고 문제 개수, 문제 형식, 난이도를 선택하신 후 '퀴즈 생성' 버튼을 눌러주세요. (난이도는 현재 퀴즈 생성에 아무런 영향을 끼치지 않고 있습니다.)
- GPT API에 요청하는 시간이 다소 소요 됩니다. (평균 몇 초 이내)

## 6. 문제 풀기
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/bf540c85-4958-43e7-9680-dc9ee3dacaa7)
- 선택한 메모, 퀴즈 옵션을 바탕으로 퀴즈를 제공 받는 페이지입니다.
- 해당 페이지에서 답변을 입력하실 수 있습니다. 객관식의 경우 선지 선택, 단답식의 경우 텍스트 입력 형태로 되어 있습니다.
- 답변을 작성하신 후에 '정답 보기' 버튼을 누르시면 정답을 보실 수 있습니다. (10초 내외로 시간 소요)

## 7. 문제 풀이 확인
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/8fec20aa-ef22-414b-bc99-35856b39aeda)
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/115972127/c9785431-5169-499c-9770-634bbef519e1)
- 이전 단계에서 제출한 정답에 대한 해설을 확인하실 수 있습니다.
- 해당 문제 풀이를 확인하기까지 다소 시간이 소요될 수 있습니다. (10초 내외로 시간 소요)

# 피드백 및 향후계획
1. 로그인 기능 구현 (유저 별 메모, 퀴즈 확인 및 생성 가능하도록 구현)
2. Embedding과 Moderation 구현
3. GPT API에서 소비되는 Token  절약하는 방법 구현
4. 답변의 정확성 검증하는  기능 구현
5. 퀴즈에 대해 사용자의 피드백을 받아 생성되는 퀴즈의 질을 높인다.

**Comment by Tastypotato245** [comment]
프론트가 이뻐서 사용성도 좋았습니다.

로딩 속도는 혹시 메모라이징으로 줄일 수 없을까요? 특정 문제에 대한 설명들은 미리 답변을 저장해놨다가 사용해도 괜찮을 것 같아요!!

<img width="1073" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/b75d1ce2-86e8-4c8d-98f4-9211d81c9894">

**Comment by dzcoffee** [comment]
코멘트 남겨주셔서 감사합니다! 메모라이징과 같이 로딩속도를 줄이는 방법은 현재 테스트 중입니다! 아마 다음에 테스트 하실 때는 개선된 속도로 이용하실 수 있을 겁니다!

**Comment by IamGroooooot** [comment]
퀴즈 재밌게 풀었습니다. 중간고사 때 있었으면 좋았겠네요 ㅎㅎ.

그런데 단답형으로 답했을 때는 답변 응답으로 옵션1이라고 뜨네요!

<img width="700" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/a3c61860-d316-42ea-8595-adb7f1417550">

**Comment by yjyoo3312** [comment]
<img width="601" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/779d4d41-4cc5-41ee-b744-5908248f6cd0">

재밌게 잘 따라했습니다! 문제도 생각보다 정확하게 잘 나오는군요

**Comment by bykbyk0401** [comment]
내용을 메모하면, 관련된 문제가 잘 생성되어 좋았습니다.
공부할 때 활용하면 좋을 것 같아 기대가 됩니다!!

기능을 사용해보며 고려하면 좋을 것 같은 부분들을 작성해 보았습니다. 개선에 도움이 된다면 좋을 것 같아요~~

<img width="366" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/592abde3-1e8d-46bf-b9ed-687545abf731">

단답형에서, 생각보다 빈번하게 풀이 요청에 실패했다는 문구가 뜨네요ㅠㅡㅠ

<img width="1129" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/c9b6a9ce-d425-43c4-a981-a37566ef75e1">

경로 압축과 랭크라는 표현이 의도된 바인지 확인하면 좋을 것 같아요~!!

++)
<img width="1136" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/84a3f213-0253-4ca6-9d17-df1a0b878afb">

올바른 답변을 입력해야만 풀이가 제공되는 것인지 궁금합니다~

수고하셨습니다!

**Comment by dzcoffee** [comment]
> 내용을 메모하면, 관련된 문제가 잘 생성되어 좋았습니다.
> 공부할 때 활용하면 좋을 것 같아 기대가 됩니다!!
> 
> 기능을 사용해보며 고려하면 좋을 것 같은 부분들을 작성해 보았습니다. 개선에 도움이 된다면 좋을 것 같아요~~
> 
> <img width="366" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/592abde3-1e8d-46bf-b9ed-687545abf731">
> 
> 단답형에서, 생각보다 빈번하게 풀이 요청에 실패했다는 문구가 뜨네요ㅠㅡㅠ
> 
> <img width="1129" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/c9b6a9ce-d425-43c4-a981-a37566ef75e1">
> 
> 경로 압축과 랭크라는 표현이 의도된 바인지 확인하면 좋을 것 같아요~!!
> 
> ++)
> <img width="1136" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/84a3f213-0253-4ca6-9d17-df1a0b878afb">
> 
> 올바른 답변을 입력해야만 풀이가 제공되는 것인지 궁금합니다~
> 
> 수고하셨습니다!

단답식의 경우에는 입력하신 답을 GPT가 검증하고 이에 대한 풀이를 주는 방식으로 구성되어 있습니다.
그 과정에서 아마 질문과 완전히 무관한 답변이 제출된 경우에는 간간히 오류가 발생하는 것으로 보입니다.
해당 부분 추후에 수정/개선 작업할 때 보완해 보겠습니다!

**Comment by sihumji00** [comment]
ui가 깔끔해서 이용하기 편리한 것 같아요! 로딩바가 포함된 알림창이 뜨는 것도 ux적으로 신선하고 기분좋게 다가왔습니다!
그런데 메모 길이를 200자로 권고하고 있어서, 짧은 메모를 바탕으로 문제 수를 많이 생성할 경우 할루시네이션에 걸리는 건지 5문제 중 4문제가 전부 같은 객관식 보기를 주는 상황이 발생하네요...! 또 욕설이 포함된 메모를 입력했을 때 모더레이션 시스템이 작동하지 않는 것 같습니다!

**Comment by dzcoffee** [comment]
> ui가 깔끔해서 이용하기 편리한 것 같아요! 로딩바가 포함된 알림창이 뜨는 것도 ux적으로 신선하고 기분좋게 다가왔습니다! 그런데 메모 길이를 200자로 권고하고 있어서, 짧은 메모를 바탕으로 문제 수를 많이 생성할 경우 할루시네이션에 걸리는 건지 5문제 중 4문제가 전부 같은 객관식 보기를 주는 상황이 발생하네요...! 또 욕설이 포함된 메모를 입력했을 때 모더레이션 시스템이 작동하지 않는 것 같습니다!

현재 토큰이 과소비될 우려로 인해 메모 길이를 제한하고 있어서 할루시네이션이 발생하는 것으로 보입니다. 토큰 소비를 줄이면 
그 만큼 입력할 수 있는 메모의 양도 늘어나서 해당 부분은 해결될 것 같습니다. 
또한, 현재 모더레이션 시스템은 적용되지 않고 있습니다. 해당 부분도 추후 구현 예정 중에 있습니다.
소중한 의견 감사합니다!

**Comment by Handoni** [comment]
프론트 디자인이 너무 깔끔하고 직관적이라서 놀랐습니다..!
다만 문제를 만드는데 쉬움이랑 어려움 문제가 3개중 2개가 똑같이 나오더라고요
이부분 조금 개선 있으면 어떨까 싶습니다
수고 많으셨습니다!!

**Comment by ahnavocado** [comment]
<img width="1175" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/66175689/a3342287-8fca-446a-afba-755a0d61fa5b">
웹사이트 내용을 전부 긁어서 진행해도 잘 나와서 좋았습니다!!
쉬움과 어려움의 차이만 조금 생긴다면 더 완벽할 거 같습니다!!
고생하셨습니다
