### ISSUE TITLE
[demo1][12조] Filchatter

### ISSUE THREAD

**Issue by rocknroll17** [PiLab-CAU/OpenSourceProject-2401#14]
# 데모 링크: https://port-0-filchatter-1fgm12klx5u6yb5.sel5.cloudtype.app
Filchatter는 텍스트 검열 api 서비스 입니다.
채팅방 링크: https://web-chattingroom-1272llx2n6xjr.sel5.cloudtype.app/

채팅방은 보내는 사람의 메시지는 검열되지 않습니다.
혹시라도 채팅방을 혼자 이용하시는 분은 창을 두개 띄워서 테스트 하시기 바랍니다.

# 사용 설명
## -Python Package
Filchatter는 PYPI로 배포되어 파이썬 패키지로도 이용하실 수 있습니다.
자세한 사용법은 
https://port-0-filchatter-1fgm12klx5u6yb5.sel5.cloudtype.app/documents/kor
 에서 확인하실 수 있습니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/a03c4f7c-8e8b-4e25-b3a2-022d1f2e5d45)
파이썬 패키지를 이용하여 보다 쉽게 필터링 기능을 직접 구현하지 않고 API 서비스를 통해서 필터링 받을 수 있습니다.
send_json_request(chat, option)을 통해서 필터링 결과를 json으로 받을 수 있습니다. option은 현재
1. 필터링 없음
2. 욕설 문장 차단
3. 별표 마스킹
4. 임의 단어 대체
각 필터링 결과는 json형식의 result 키에서 찾으실 수 있습니다.

### Home
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/d2aeebe9-ed18-4244-aa08-e76c4a04492a)
https://port-0-filchatter-1fgm12klx5u6yb5.sel5.cloudtype.app 접속
Home에서 본인이 보내는 채팅에 대한 욕설의 포함 유무를 답변으로 확인하실 수 있습니다.
채팅을 통해서 Filchatter의 기능을 간단하게 체험해보세요!

### API KEY 발급
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/3f656c50-7105-4573-aee1-a8ef180d6dcc)
https://port-0-filchatter-1fgm12klx5u6yb5.sel5.cloudtype.app/documents/kor/generate_key 접속
본인의 사용자 이름을 입력하여 API KEY를 발급합니다.
해당 API KEY는 잃어버리면 다시 찾을 수 없습니다. 그렇기 때문에 꼭 다른 곳에 저장하시기 바랍니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/e1951de8-04f6-4ef0-8fe7-b6ffe66fe514)

### Documents
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/cd8d37b1-6b5e-4dbb-857b-f0de2adfafed)
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/c4101090-77a5-4576-8965-ee0078d727fd)

https://port-0-filchatter-1fgm12klx5u6yb5.sel5.cloudtype.app/documents 접속
Filchatter 모듈을 사용하는 방법에 관한 문서를 다루고 있습니다. 영어가 어려우신 분은 우측 상단의 한글 페이지로 가셔서 확인하실 수 있습니다.

## 채팅 서비스에 적용된 Filchatter 사용하기
해당 기능은 직접 채팅 서버에 적용된 Filchatter를 이용할 수 있습니다.
### 접속방법 
1. https://web-chattingroom-1272llx2n6xjr.sel5.cloudtype.app/ 접속
2. 이름 입력 후 입장
3. 옵션 설정
4. 채팅 보내기

# 개발 상황
수정 예정

# 피드백
수정 예정

**Comment by Tastypotato245** [comment]
## 테스트
<details>
<summary>욕설 주의 </summary>
<div markdown="1">

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/5953d766-e3e9-4d64-a30f-75ddd572f049)

크크 고차원 욕설에는 아직 반응하지 못하는군요

<img width="1115" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/ca3f2132-823e-448c-a1d4-51ddb4cf2a5e">

그리고 이 케이스는 어제 했을 때는 됐는데 오늘은 또 안되네용

<img width="1112" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/28c6e251-1aac-4668-8d0e-f33e5e95318c">

이건 나름 모욕적인거라 생각했는데 사람마다 생각하는 기준이 애매해서 이것도 역시 애매하네요

<img width="1107" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/88925e83-3869-4b04-973f-ce2dcc404ca0">

이것도요

</div>
</details>

일반적인 욕설은 잘 잡아내지만, 그런 부분은 지금 현재 string match 알고리즘으로 충분히 커버 가능한 영역이라 생객해서, 좀 더 개선되면 좋을 것 같아요!

**Comment by yjyoo3312** [comment]
예, 재밌게 잘 테스트 하였습니다! (테스트 내용을 올리기에는 좀 애매해서 후기만 올립니다)

일반적인 욕설들이 섞인 문장들은 잘 대응을 하는 것 확인하였습니다. 앞으로 직접적으로 욕이 섞이지는 않은 부적절한 문장들도 필터링이 가능하다면 용도가 맣을 것 같네요

**Comment by leesuji2000** [comment]
현재 서버가 열려있지 않아서 사용할 수 없음으로 뜹니다.ㅜ

**Comment by cozy-hn** [comment]
지금도 마찬가지 입니다 ㅠㅠ

**Comment by MarcelMaxx** [comment]
링크 열수 없네요ㅠㅠㅠ
<img width="703" alt="Screenshot 2024-05-09 at 10 15 01 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/dc386b32-fd11-427a-98bb-4159a5c1b8e3">

**Comment by rocknroll17** [comment]
@leesuji2000 @cozy-hn @MarcelMaxx 
죄송합니다 제가 네트워크 설정을 잘못 만진 상태로 아침부터 켜놨더군요.
확인하자마자 바로 고쳤습니다.
죄송합니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/53882578/4c7e6738-305b-42f0-9a79-5a0353b5ec61)
