### ISSUE TITLE
[demo1][8조] Newstrality 

### ISSUE THREAD

**Issue by ahnavocado** [PiLab-CAU/OpenSourceProject-2401#16]
Newstrality 
=============
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/66175689/a75eb558-9e84-4043-a948-f242dac751cc)

# 데모 링크
http://13.209.91.211:3000
# 사용 방법
1. 웹 페이지에서 정치/사회 면의 가장 최근 뉴스 기사를 10개를 확인 할 수 있다. 
2. 관심 있는 기사를 클릭하여 중립적으로 변환되어있는 기사 요약본을 확인 할 수 있다.
3. 원본 기사와 비교하여 중립을 유지하기 위하여 기사를 바꾼 이유에 대한 설명을 확인할 수 있다. 

# 스크린샷
## 초기 화면
초기 접속시 화면이다. 
<img width="1434" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/66175689/fb628316-0383-4706-88d8-6c9920364a39">
## 기사 클릭 시 
중립적으로 요약되어있는 기사와 그렇게 요약된 요소들을 출력한다. 
<img width="1438" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/66175689/79142aff-4000-46f2-88b6-b01121a14e5c">

# 현재 구현된 사항
1. 사용자는 홈화면에서 해당 관심사 뉴스 중 최신 10개의 기사 헤드라인을 볼 수 있다. 
2. 중립적으로 변환된 기사에 대한 내용을 확인할 수 있다.

# 최종 목표 
대한민국 국민의 편향된 정치관 타파 및 건강한 정치관 확립

# 향후 계획
## 추가 기능 구현
1. 사용자는 외부 기사를 검색하고 해당 기사를 확인할 수 있다
2. 사용자는 로그인을 통해 회원 기능을 이용할 수 있다.
3. 사용자 로그인을 통해 사용자가 제공된 기사가 중립적이지 않다고 판단되는 경우 피드백을 남길 수 있다.
4. 사용자는 해당 언론사의 편향정도를 확인 할 수 있다.

## 성능 개선
계속하여서 gpt 프롬프트 엔지니어링을 통하여서 성능을 개선한다.

**Comment by Tastypotato245** [comment]
<img width="857" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/6db6cc77-16e3-4987-ba10-8d098bc9401c">

생각보다 좋은 퀄리티로 잘 나오는 것 같아요! 인풋이 사용자가 아직 아니라서, 프롬프팅 공격이나 다른 취약성에 대해 테스트는 아직 해보지 못했지만, "보편화" 측면에서 꽤나 GPT의 특성이 잘 드러나는 것 같아서 좋네요.

재미있게 잘 봤습니다!!

**Comment by yjyoo3312** [comment]
<img width="760" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/c9244f30-fb66-4ab4-a5be-e437ec996c96">

설명과 출력물이 퀄리티가 좋네요!  현재 Newstrality 에 의해 바뀐 뉴스들은 모두 DB에 저장이 되고 있는 것일까요?

**Comment by MarcelMaxx** [comment]
조은 아이디어가 이네요~ 목표도 매우 고무적입니다! 근데 혹시 원본 뉴스나 변환된 뉴스를 아직 못 보나용?
<img width="1194" alt="Screenshot 2024-05-09 at 10 06 10 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/168d758d-c721-4c4a-90d9-152a0f26f7df">

**Comment by Tastypotato245** [comment]
저도 같은 의견입니다!!! 원본 기사에 대한 링크들을 리스트로 우측에 띄워주면 좋을 것 같아요!

**Comment by Haemulramen** [comment]
@yjyoo3312 네 저희 newstrality 에서 제공하는 요약된 뉴스는 모두 DB에 저장되고 있습니다

**Comment by Haemulramen** [comment]
@MarcelMaxx 원본 뉴스는 링크를 연결해서 사용자가 확인할 수 있도록 개선할 예정입니다! 이용해주시고 피드백 주셔서 감사합니다

**Comment by Haemulramen** [comment]
@Tastypotato245 원본 기사에 대한 링크에 관련해서 의견 주셔서 감사합니다 프로젝트 진행하면서 개선하도록 하겠습니다!
