### ISSUE TITLE
[demo1][4조] Blogit

### ISSUE THREAD

**Issue by euije** [PiLab-CAU/OpenSourceProject-2401#17]
# 데모 링크

- https://blogit-website.vercel.app/

# 사용 설명

https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12531340/d67da4d0-4f99-436a-b442-6bec406e31c3

중간 데모: 디자인 없는 전체적인 구성, 깃허브 api , gpt 일부, 서버 기초 작업

최종 목표까지 남은 목표: 디자인, gpt 마무리, 서버와 클라이언트 연결

+ 사용자 피드백 반영

데모 링크로 들어가면 메인페이지가 뜬다. 

메인페이지의 하단에 깃허브 아이디를 적고 GO버튼을 누른다.
두번째 페이지에서 본인의 레포지토리에서 생성한 커밋들이 나타나면, 글을 작성하고 싶은 커밋들을 선택한다. 해당 커밋을 다시 한 번 클릭하면 글 작성 목록에서 제외할 수 있다. 

글을 작성할 커밋들을 모두 선택했으면 글 작성하기 버튼을 통해서 다음 페이지로 넘어간다.

세번째는 사용자가 선택한 Commit 이력의 코드를 기반으로 GPT가 글을 작성한다

네번째 페이지로 넘어오면 생성한 글을 직접 수정할 수 있다. 수정하고 확인을 누르고 글을 마무리한다. 중간 데모에서는 서버와 연결을 하지 않았기 때문에 글이 저장되지 않는다.

글을 마무리하면 본인이 쓴 글들과 업로드하러 갈 수 있는 링크들이 있다. 클릭하면 해당 페이지로 넘어간다. 그 아래에는 지피티가 방금 쓴 글에 대해 글감을 추천해지만 중간 데모에선 구현하지 않았다. 하단에 다시 글 작성하기 버튼을 누르면 메인페이지로 들어가서 다시 글을 작성할 수 있다.

# 알려진 버그
- Github 계정에 1개의 커밋도 없는 repository를 소유하고 있으면 오류가 발생
- 작성 완료한 파일을 다운로드하면, 한글이 깨져 정상적으로 보이지 않는다

**Comment by euije** [comment]
@Bowoon1216
@bykbyk0401
@MarcelMaxx

**Comment by WickedFoxes** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/9fc188dd-9dc5-4e6b-bbbc-a247888f0f56)
- 글을 다운로드하면 확장자는 md 파일이지만, 실제로는 html 태그 형식으로 작성되어 있습니다.
- 출력 형식을 markdown 형식으로 작성되도록 하거나, 파일명을 .html로 변경하는 것이 좋아 보입니다.

**Comment by Tastypotato245** [comment]
제가 prim 알고리즘으로 백준 문제 푼 커밋을 선택했는데요, 굉장히 잘 분석해주네요!!

<img width="1192" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/03398933-aa84-4b53-9772-bcfbc767c2ce">

계정 연동도 그렇고 신기합니다!!

크롤링하시는데 고생하셨을 것 같아요.

재밌었습니다!! 

얼른 다운 기능이 돌아왔으면 좋겠어용

**Comment by IamGroooooot** [comment]
잘 작동되고 완전 신기합니다. 
블로그 글 쓸 때 한번 사용해봐야겠습니다ㅎㅎ  

다만 엄청 긴 코드를 작성한 경우는 터지는 것 같아요!   
ex) 프레임워크에서 Project 처음 생성하고 업로드용으로 만든 커밋

<img width="400" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/79d35769-b9fe-4c14-899a-371095ece9f0">

**Comment by yjyoo3312** [comment]
잘 작동이 되는군요! 그냥 readme 파일 변경 등의 내용을 물어봐도 생각 이상으로 잘 대응하는군요. Commit 이력 받아오는데 길이의 제한 같은 것도 있을까요?
<img width="1040" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/5b30a159-89d2-46b0-a17d-8b40a8489138">

**Comment by kimseongsun** [comment]
안녕하세요 이용하다가 질문드립니다
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/165504743/131704e3-ab8e-4cea-91e2-7e7bde9dd4b7)
데모 테스트를 위해서 Demo-4-Test 레포지토리 생성하고 commit을 하고 Blogit을 이용했는데
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/165504743/8c06e61a-97ef-44ea-84d0-ef2e5ae7e1e8)
다음과 같이 commit된 이력이 나오지 않더라구요.. 레포지토리가 private이라서 그런가 싶어서 public으로 바꿔봤는데도 해결이 안되서요
Default Branch로 설정되어있는 main branch에 등록된 커밋만 인식하는건가요?

**Comment by Bowoon1216** [comment]
@WickedFoxes  피드백 감사합니다! 
추후에 해당 부분에 대해 논의해보겠습니다 👍

**Comment by Bowoon1216** [comment]
@Tastypotato245 안녕하세요! 피드백 감사합니다😄 
추후에 나올 서비스도 기대해주세요 👍

**Comment by Bowoon1216** [comment]
@yjyoo3312 네 교수님 피드백 감사합니다 👍 
커밋이력 받아온느데 제한은 아직 없는데 토큰수를 카운트하는 기능을 추후에 추가할 예정입니다!

**Comment by Bowoon1216** [comment]
@kimseongsun 안녕하세요! 피드백 감사드립니다!
네, 커밋이 default branch에서만 불립니다!

**Comment by kimseongsun** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/165504743/722bbafc-2f4a-4115-abea-9d970fa76a75)
안녕하세요 default branch에 커밋된 내용들이 불러와지지 않습니다ㅠ 

다른 분들은 잘 되는데 제가 뭘 잘못한 걸까요?
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/165504743/471dfa37-8b68-4c29-b142-9cc99b316900)

https://github.com/kimseongsun/Demo-4-test-2 
gitHub링크는 다음과 같습니다

**Comment by euije** [comment]
@kimseongsun 안녕하세요 4조 이의제입니다.
해당 Repository의 2개의 commit의 commiter가 'web-flow'로 나와서 불러와지지 않는 것 같네요.
웹으로 업로드하셨다면, PC로 시도해보시고, commit PC의 git config가 본인 Github ID로 잘 설정되었는지 확인해주시면 감사드리겠습니다!

<img width="691" alt="스크린샷 2024-05-09 오후 7 28 29" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12531340/a50a7d17-fad9-479c-af47-b26cb84cc40f">

**Comment by euije** [comment]
5월 28일부로 아래 내용이 업데이트 되었습니다 :)
많은 관심 부탁드립니다

- title, favicon 변경
- 다운로드 정상화
- 커밋 선택페이지 UI 개선
- 마크다운 편집기
- GPT 생성 Streaming
- 프롬프트 업데이트
- 글쓰기 팁 보여주기

**Comment by euije** [comment]
5월 30일부로 아래 기능 사용 가능합니다

- 회원가입 / 로그인
- 글 저장
- 글 불러오기
