### ISSUE TITLE
[demo1][5조] 📔DearMe📔

### ISSUE THREAD

**Issue by LUCETE012** [PiLab-CAU/OpenSourceProject-2401#18]
## 데모 링크

https://bit.ly/cauDearMe

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/84865066/8584e905-2024-4c66-9d55-55bb46f862f4)

## 사용 설명

DearMe 서비스 이용 방법😊

1. 구글 계정을 통해서 서비스에 로그인을 진행합니다.
2. DearMe와 채팅을 통해 오늘 하루에 10번 이상의 충분한 대화를 나누고 나면 “generate” 버튼이 활성화 됩니다.
3. “generate” 버튼을 누르면 일기가 생성됩니다.

## 향후 계획

향후 추가할 개선사항입니다☘️

- 자신의 페르소나를 입력하는 기능 추가
- 하루를 대표하는 사진을 전송하고 저장
- 일기 생성과 사진 전송이 완료되면 피드에서 일기 확인
- 디폴트 사진 추가
- 날짜를 선택하여 피드를 볼 수 있는 캘린더 기능을 추가
- UI/UX 개선

**Comment by Tastypotato245** [comment]
<img width="414" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/8aaa0118-38e7-4e34-9738-1cd2132294a3">

재밌네요!

추후에 인스타그램 API이용해서 스토리로 올리는 연동 기능도 가능하면 좋겠어요!!

**Comment by minseok128** [comment]
@Tastypotato245 
 소중한 일기 공유 감사합니다!🥳

**Comment by bykbyk0401** [comment]
있었던 일을 대충 작성해도 그럴듯한 한 편의 일기가 나오는 재미가 쏠쏠하네요:)

++) 사용해보면서 느낀 점들을 작성해 보았습니당. 앞으로의 개발에 도움이 되면 좋겠습니다.

<img width="383" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/aade1b69-0f47-4ab1-a420-88e9bd36038f">

글을 길게 적으면 단어를 치고 띄어쓰기를 할 때, 글자가 씹히는? 현상이 있는데, 불편함이 느껴지지 않도록 개선되면 좋을것 같아요!!

<img width="399" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/cf5c26f4-92e8-40f4-9be3-70993c5f28ce">

한꺼번에 지피티의 질문이 너무 많은 것 같아 가독성이 떨어지는 느낌이 들 수도 있는것 같아요~

<img width="397" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/c2e82b41-eb5e-408a-85bc-59ae2df36fa6">

같은걸 반복적으로 묻거나 더이상 할 말이 없어지는 부분도 빈번하게 생기는 것 같아요!!

결론적으로 아직까진 DearMe를 사용하면서 나의 이야기를 이끌어내게 되기보단, 내가 대화를 이끌어나가는 느낌, 그냥 일기를 적는것과의 큰 차이점이 느껴지지 않는다는 점이 조금 아쉽습니다.
생성하기 버튼이 어떤건지 몰라서 계속 작성하고 있었던 점을 고려했을 때, 생성하기 버튼이 부각되면 좋을 것 같다는 생각이 들었습니다!!

앞으로의 개선이 기대됩니다~~ 감사합니다:)

**Comment by yjyoo3312** [comment]
현재도 일기의 생성 퀄리티가 좋네요 (일기는 포스트 하려니 뭔가 부끄러워서 공유는 안드리는 걸로) ! 향후 계획들이 잘 구현이 되면 더 흥미로울 것 같습니다.

**Comment by pius338** [comment]
@bykbyk0401 향후 개발에 참고하겠습니다! 정성스러운 피드백 감사드려요😊

**Comment by Haemulramen** [comment]
서비스 후기가 정말 좋아서 저도 큰 기대를 품고 서비스 이용을 해봤어요!!
ai가 질문을 만들어서 일기를 작성하는데 필요한 소스를 이끌어내는 것도 좋고 어느 정도의 공감을 해주는 것도 참 좋아요
그런데 이전에 다른 분이 말씀해주신 것처럼 같은 질문을 반복하는 경우가 있어서 개선된다면 더 즐겁게 사용할 것 같아요

마지막으로 저는 11번 정도 대화를 했는데도 generate 버튼이 생기지 않아서 직접 "generate"를 입력했는데 사진과 같은 응답이 나와서 조금 당황스러웠어요
![5조 캡처본](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/128495883/0b33ef1f-180d-4ac7-8f00-adb3975037d8)

**Comment by minseok128** [comment]
@Haemulramen

안녕하세요! 왼쪽 하단에 + 버튼이 생성 버튼입니다!! 가시성이 떨어진다는 피드백이 많아서, 확실히 수정하려고 합니다!

현재 대화하신 내용은 다시 접속하시면 그대로 남아있으므로, + 버튼 눌러서 일기 한 번 생성해주시면 감사하겠습니다!!!

**Comment by Haemulramen** [comment]
@minseok128 헉 죄송합니다!!
잘 되네요 서비스 정말 좋아요 😀

**Comment by kendsi** [comment]
GPT가 질문을 던져줘서 일기 쓰기도 편했고, 쓰면서 생각을 정리하기도 좋았습니다! 그런데 생성된 일기 오른쪽 위 펜 아이콘을 누르면 사용자가 직접 수정할 수 있다고 생각했는데 맞을까요? 해당 기능이 잘 작동하지 않는 것 같습니다.

![제목 없음1](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/144663920/a4d3f94d-aa8a-4b97-959d-f25d4c1cc820)

위 사진처럼 일기를 수정하였는데,

![제목 없음](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/144663920/67d42a3d-b0d5-4690-aad3-9b5c5ef9e146)

이렇게 원래대로 돌아가고 새로고침해도 바뀌지 않습니다.

늦은 시간에 댓글 적어서 죄송합니다 ㅜㅜ

**Comment by cozy-hn** [comment]
@kendsi 
안녕하세요. 먼저 테스트 정말 감사합니다. 
지적하신 부분처럼 일기를 수정하는 작업은 동작하지 않습니다. 이 기능은  프론트 단에서 버튼만 구현되어 있고 추후 업데이트 될 예정입니다.
수정한 일기를 바탕으로 더 개선된 본인의 다음 일기를 만들 예정이니 추후에 다시 사용해주시면 감사하겠습니다!
