### ISSUE TITLE
[demo1][2조] ChatClips

### ISSUE THREAD

**Issue by hyounsoo0625** [PiLab-CAU/OpenSourceProject-2401#19]
1-1. 데모 링크: http://gamgyul.s3-website.ap-northeast-2.amazonaws.com

1-2. 사용 설명:
1. 화면을 두 개 이상 띄우거나 기타 모바일 기기가 있으면 두개로 링크에 접속한다.
2. 회원가입을 다른 아이디랑 이름으로 2개 이상 가입한다.
3. 2개 이상의 계정으로 로그인을 진행한다.
4. 계정 중 하나로 방을 만든 후, 방 아이디를 공유한다. (단, 방을 만들 때 방 아이디를 복사한다.)
5. 다른 계정도 방 아이디를 치고 해당 방에 들어간다.
6. 채팅을 자유롭게 진행한다.
7. 채팅을 끝내고 싶으면 채팅 종료 버튼을 클릭한다.

<hr>

![KakaoTalk_20240508_121700947_07](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/79c5b67d-72fe-4c8e-b5e9-2854503006bc)

![KakaoTalk_20240508_121700947_06](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/486fbfc5-b901-468b-935f-80331a4d1d9e)

![KakaoTalk_20240508_121700947_05](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/27006e66-f950-409f-8d45-bc19cda84bf8)

![KakaoTalk_20240508_121700947_04](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/1e973d86-7f28-4fe1-bf17-f70b1669512c)

![KakaoTalk_20240508_121700947_03](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/ba118016-edf0-40fe-8bee-a8be0619c651)

![KakaoTalk_20240508_121700947_02](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/de11395a-49b4-4d5e-9927-49b1ad9d806a)

![KakaoTalk_20240508_121700947_01](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102412616/517f138c-7410-4580-bf23-2a522c44ed48)

<br>
<hr>
향후 최종 데모까지 계획
1. 방 입장하면 방 아이디 상단 노출
2. 한 사람이 회의 끝내기를 누르면 전체 유저 회의 종류 구현

**Comment by Tastypotato245** [comment]
<img width="845" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/1c446466-6dae-4a5a-93ac-4ee11e029011">

<img width="845" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/7ede4560-975f-42f4-b062-f2a10257c02d">


회원 가입 이후 로그인 시 화면 전환이 되지 않아요!! 로그인을 누르면 그냥 빈 필드로 변경되고 사이트 이동이 안되네용

**Comment by hyounsoo0625** [comment]
> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596303-1c446466-6dae-4a5a-93ac-4ee11e029011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDEyOTYsIm5iZiI6MTcxNTEwMDk5NiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMDMtMWM0NDY0NjYtNmRhZS00YTVhLTkzYWMtNGVlMTFlMDI5MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmExYzE4MWNmMWIwYjg3NzFhNTMzZmNhMjY5YjJiYWRlZWY3NDAyMjJkODcyMWE5ZmQzYzYyMWFlYmZmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v3VPw3qc2lQRH79xLWao2gK-0QoGEtS2vt9FTY4RUEA"> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596330-7ede4560-975f-42f4-b062-f2a10257c02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDEyOTYsIm5iZiI6MTcxNTEwMDk5NiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMzAtN2VkZTQ1NjAtOTc1Zi00MmY0LWIwNjItZjJhMTAyNTdjMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlN2MzODQxMWY2Y2FhMjdlYzA5NzA2YjRkYjk4OTkxYTg2NWQzZGI5ODAwN2VmMmFmNjRkZjk0YTc2OGQ0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLwewPijJFfPFMJGvnTc4JlOqdimpsmgwV1suQYUKso">
> 회원 가입 이후 로그인 시 화면 전환이 되지 않아요!! 로그인을 누르면 그냥 빈 필드로 변경되고 사이트 이동이 안되네용

현재 수정 중입니다. 빠른 시일 내에 수정하겠습니다. 수정하면 재공지하겠습니다.

**Comment by Tastypotato245** [comment]
> > <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596303-1c446466-6dae-4a5a-93ac-4ee11e029011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDEyOTYsIm5iZiI6MTcxNTEwMDk5NiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMDMtMWM0NDY0NjYtNmRhZS00YTVhLTkzYWMtNGVlMTFlMDI5MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MmExYzE4MWNmMWIwYjg3NzFhNTMzZmNhMjY5YjJiYWRlZWY3NDAyMjJkODcyMWE5ZmQzYzYyMWFlYmZmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v3VPw3qc2lQRH79xLWao2gK-0QoGEtS2vt9FTY4RUEA"> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596330-7ede4560-975f-42f4-b062-f2a10257c02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDEyOTYsIm5iZiI6MTcxNTEwMDk5NiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMzAtN2VkZTQ1NjAtOTc1Zi00MmY0LWIwNjItZjJhMTAyNTdjMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE2NTYzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlN2MzODQxMWY2Y2FhMjdlYzA5NzA2YjRkYjk4OTkxYTg2NWQzZGI5ODAwN2VmMmFmNjRkZjk0YTc2OGQ0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLwewPijJFfPFMJGvnTc4JlOqdimpsmgwV1suQYUKso">
> > 회원 가입 이후 로그인 시 화면 전환이 되지 않아요!! 로그인을 누르면 그냥 빈 필드로 변경되고 사이트 이동이 안되네용
> 
> 현재 수정 중입니다. 빠른 시일 내에 수정하겠습니다. 수정하면 재공지하겠습니다.

넵!! 고생 많으십니다~~

**Comment by yjyoo3312** [comment]
아직 로그인이 저도 되지 않는군요;; 내일 다시 테스트 해 보겠습니다:)

**Comment by Bowoon1216** [comment]
엇 저는 회원가입 시도해보았는데 보안 메시지가 뜨네요..?
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/105543811/e9115898-c613-4e46-ba19-2e6a5c71ee6a)
추후에 수정 완료되면 다시 테스트 해보고 싶네요 😄

**Comment by kimseongsun** [comment]
서비스 언제쯤 이용할 수 있을까요?

**Comment by Richardyun01** [comment]
로그인이 안되서 여전히 서비스를 이용할 수가 없네요...

**Comment by hyounsoo0625** [comment]
> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596303-1c446466-6dae-4a5a-93ac-4ee11e029011.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjQxNzgsIm5iZiI6MTcxNTIyMzg3OCwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMDMtMWM0NDY0NjYtNmRhZS00YTVhLTkzYWMtNGVlMTFlMDI5MDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzMDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNDE1MTljZDRmNWFjYmUxYmY3MzI4YTE1OWI0MjZkNzViMzZiMzNjNmJkZWRjZDJiNWRjYjY5NmVlZGQyMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9oWCQpKcC6WwrwzZYy0QauVQ_h5YJparVf6uCQ9u99o"> <img alt="image" width="845" src="https://private-user-images.githubusercontent.com/63251068/328596330-7ede4560-975f-42f4-b062-f2a10257c02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjQxNzgsIm5iZiI6MTcxNTIyMzg3OCwicGF0aCI6Ii82MzI1MTA2OC8zMjg1OTYzMzAtN2VkZTQ1NjAtOTc1Zi00MmY0LWIwNjItZjJhMTAyNTdjMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDAzMDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDZjZjZmNDA3YTYyYTE4NmQxYWQzMWYwNWVjNjkwZWFiMGUwOGM3NGMzMTRhMWZmMzE4NzE0NzkzNWFhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kuc6chi_j77AMYTD_a6f3zmZAeNBlxDR3by9CsmRRG0">
> 회원 가입 이후 로그인 시 화면 전환이 되지 않아요!! 로그인을 누르면 그냥 빈 필드로 변경되고 사이트 이동이 안되네용

현재 해당 부분 수정 완료 되었습니다!

**Comment by hyounsoo0625** [comment]
> 로그인이 안되서 여전히 서비스를 이용할 수가 없네요...

현재 해당 부분 수정 완료 되었습니다!

**Comment by hyeonsoo0625** [comment]
> 로그인이 안되서 여전히 서비스를 이용할 수가 없네요...

현재 해당 부분 수정 완료 되었습니다!

**Comment by hyounsoo0625** [comment]
> 서비스 언제쯤 이용할 수 있을까요?

현재 이용할 수 있습니다!

**Comment by hyounsoo0625** [comment]
> 아직 로그인이 저도 되지 않는군요;; 내일 다시 테스트 해 보겠습니다:)

현재 해당 부분 수정 완료 되었습니다!

**Comment by hyounsoo0625** [comment]
> 엇 저는 회원가입 시도해보았는데 보안 메시지가 뜨네요..? ![image](https://private-user-images.githubusercontent.com/105543811/328977994-e9115898-c613-4e46-ba19-2e6a5c71ee6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMjQxNzgsIm5iZiI6MTcxNTIyMzg3OCwicGF0aCI6Ii8xMDU1NDM4MTEvMzI4OTc3OTk0LWU5MTE1ODk4LWM2MTMtNGU0Ni1iYTE5LTJlNmE1YzcxZWU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQwMzA0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2E0NjlkOGRhYjUzYTQ2ZWVjZmZmNGYzMGQ1NGY4YzQzZWRlYjNmN2YzZDc5OTk4ZGVhNmMyMDc2OGRmNDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rcghm1BjyJHZ1q16zXL8CQH8MP9-5a-71FVHHzCi13M) 추후에 수정 완료되면 다시 테스트 해보고 싶네요 😄

현재 해당 부분 수정 완료 되었습니다!

**Comment by Jeong-In-Lee** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/80769394/69fce90b-e003-4caf-a968-ad611d4e77ff)
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/80769394/c392b9c9-07d6-4dea-b62b-3cd6b009d3ca)
채팅도 잘 진행되고, 회의 요약도 잘 되는 것 같습니다. 다만, 채팅 끝내기를 누른 뒤에, 다시 그 방으로 들어가려고 하면 채팅방은 새로 생기지만 전부 회의가 끝난 상태로 나옵니다. 근데 이제 채팅방에 아직 남아있는 사람한테는 다시 들어온 사람이 잘 들어왔다고 나오네요.

**Comment by yjyoo3312** [comment]
<img width="388" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/876bfd61-6d3e-4a58-95fd-35723ffff7c9">

ChatGPT 요약 기능이 잘 작동하는지 위주를 보기 위하여 한명이서 여러 메세지를 남겨봤습니다. 기본적인 요약 기능이 구현이 잘 된것 같습니다. 기능상으로는 나중에 채팅 참여자 각각이 얘기한 내용들을 따로 요약을 해줘도 유용할 것 같다는 생각이 드네요

**Comment by llswll023** [comment]
> ![image](https://private-user-images.githubusercontent.com/80769394/329137763-69fce90b-e003-4caf-a968-ad611d4e77ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDM0MzEsIm5iZiI6MTcxNTI0MzEzMSwicGF0aCI6Ii84MDc2OTM5NC8zMjkxMzc3NjMtNjlmY2U5MGItZTAwMy00Y2FmLWE5NjgtYWQ2MTFkNGU3N2ZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNjNkYmI4Zjk0OGU2ODRhY2NhN2ZiN2Y5NGQwOTgzMTg3ZGMzZmQ1NjFhNzhlOTBjMzMwYTE4MDFlZGYwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DEmt0AvbGftA2XLR6viRCuDKcFy1PQF42-YnZ-CLRbQ) ![image](https://private-user-images.githubusercontent.com/80769394/329137807-c392b9c9-07d6-4dea-b62b-3cd6b009d3ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDM0MzEsIm5iZiI6MTcxNTI0MzEzMSwicGF0aCI6Ii84MDc2OTM5NC8zMjkxMzc4MDctYzM5MmI5YzktMDdkNi00ZGVhLWI2MmItM2NkNmIwMDlkM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDdlNzFjNzMyNzVhYjM2YTc0YjAxNGMwMjUyZjY1OGU3MmE5MWY1NjAzYTY2NGJmYWUxNWFmMDM2ZjVhYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9kH4lf2JCRCZcDbIAN4rHdy4AKZIsTOdqnUMRJZEySs) 채팅도 잘 진행되고, 회의 요약도 잘 되는 것 같습니다. 다만, 채팅 끝내기를 누른 뒤에, 다시 그 방으로 들어가려고 하면 채팅방은 새로 생기지만 전부 회의가 끝난 상태로 나옵니다. 근데 이제 채팅방에 아직 남아있는 사람한테는 다시 들어온 사람이 잘 들어왔다고 나오네요.

네, 감사합니다! 우선 말씀해주신 채팅방 종료 기능에 대한 보완은 추후 개발 계획에 작성해놓은 대로 데모데이 이후 진행될것같습니다!  더 나은 서비스를 제공하기 위해 노력하겠습니다. 협력해 주셔서 감사합니다!

**Comment by Handoni** [comment]
현재 회원가입이 안되는것 같습니다..!

**Comment by hyounsoo0625** [comment]
> 현재 회원가입이 안되는것 같습니다..!

현재 서버에서 웹소켓이 채팅을 나가도 안끊기는 문제가 발견되었습니다. 현재 임시로 서버를 닫았다가 다시 열어 로그인이 가능합니다. 중간데모가 얼마 안 남았고 최종데모때 보다 완벽한 환경을 제공하기 위해 중간데모때는 일시적으로 서버를 계속 리부트 할 계획입니다. 감사합니다.
