### ISSUE TITLE
[demo1][7조]이야기 놀이터

### ISSUE THREAD

**Issue by suminl22** [PiLab-CAU/OpenSourceProject-2401#20]
<br/>

안녕하세요 :)
저희는 ‘이야기 놀이터’ 서비스를 개발 중인 오픈소스 SW 프로젝트 7조 입니다.

이번 데모에서 보여줄 main 기능은
챗봇과 상호작용하며 **'하나의 완결된 이야기 만들기’** 입니다.
위 기능을 중심으로 데모 서비스를 이용해주시면 됩니다 :)

<br/>

# 프롬프트 v1.1 출시
![2](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/66d85230-15bd-4c62-adfc-d1c5ce74ba98)

### 업데이트 내용

💡 이야기의 구성 단계 '발단-전개-위기-절정-결말'의 흐름을 따라 이야기를 창작해나갑니다!
💡 현재 이야기가 어느 단계인지 명시해줍니다. (ex. 토끼는 깜짝놀랐어요#전개 #3번째대화)
💡 이야기 완결 명시 : gpt가 이야기를 완결하면서 '##이야기 종료##'를 출력합니다!
   -> 이야기가 종료되면, 반드시 '새로고침(F5)'을 눌러 이야기를 다시 시작해주세요!
       
이밖에도, 이야기의 문맥을 유지하고 사용자 수준에 맞는 단어와 문장을 선택하는 등 전반적인 사용자 경험을 높였습니다 :)

<br/>

# 데모 링크
http://204.236.203.188   
<br/><br/><br/>

# 사용 설명

- 아래의 **사용 전 참고 사항을 반드시 확인**하시고 서비스를 이용해주시기 바랍니다.
- 아래의 **사용법 및 주의 사항을 참고**하여 서비스를 이용해주시기 바랍니다.
- url 조작을 통한 페이지 접근을 지양해주시기 바랍니다.
반드시 생성된 계정을 이용해야 올바르게 작동하는 서비스를 이용하실 수 있습니다.

<br/>

## 사용 전 참고 사항

```
💡 ‘이야기 놀이터’는 만 4~7세 아동을 대상으로 만들어진 대화형 이야기 창작 소프트웨어입니다.
    사용해보실 때, 반드시 본인이 ‘만 4~7세 어린이’라고 상상하며 이야기를 만들어나가주세요 :)
```
<br/>

### **회원가입** 해주세요!

- 반드시 **계정 생성 조건**에 맞게 생성해주세요!
- 계정 생성 조건
    - 아이디 : ‘영문대소문자+숫자’ (4자 이상 8자 이내)
    - 비밀번호 :  ‘영문대소문자+숫자’ (4자 이상 8자 이내)
    

![1](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/b54eaed4-0812-479d-9355-33c6b4d4c9d1)

![2](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/c56aa94b-09c0-432a-82b1-70983f57cde7)

<br/>

### **로그인** 해주세요!

![3](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/6bc0a61c-9999-47b5-a41b-d4187aaf345e)

<br/>

### **‘이야기 시작하기’** 버튼을 눌러주세요!

- 이야기와 관련된 기능 3가지(생성하기, 재개하기, 열람하기) 기능 중
    - 현재 **’생성하기’** 기능만 이용 가능합니다.
    - 메인 페이지 가운데에 있는 **‘이야기 시작하기’ 버튼**을 눌러 이야기를 만들어보세요.
- 가운데 있는 두 개의 tab(작성 중, 작성 완료)은 각각
사용자가 만들다가 중단한 이야기와 작성 완료한 이야기를 저장하여 보여주는 기능입니다.
→ **해당 기능은 아직 구현되지 않았습니다.**

![4](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/1e46b22c-6bba-4502-9f21-f686cb5c7966)

<br/>

### 챗봇 ‘야기’와 문장을 주고 받으며 나만의 이야기를 만들어 보세요!

- 시작 조건 : 챗봇 '야기'의 문장으로 시작
- 이야기 전개 : '발단-전개-위기-절정-결말' 단계에 따라 진행되다가 챗봇의 ##이야기 종료## 로 이야기 완결을 표시
- 입력 문장 길이 제한 : 한글 20자 이내
- 욕설 및 이상한 문장 제한 : hallucination 미완성
- 반드시 자신이 ‘4~7세 어린이’라고 상상하며 이야기를 만들어주세요! :)

![3](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/d1010646-c586-454e-9b1f-027827b2546f)
![2](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/66d85230-15bd-4c62-adfc-d1c5ce74ba98)

```
   위 예시 사진에서 시스템 출력 문장에 포함된 #전개,#1번째 대화   #전개,#2번째 대화
   태그는 이야기 전개 단계를 사용자에게 보여주기 위한 의도적인 출력문장입니다.
   본 데모에서는 전개 단계 잘 지키며 gpt가 이야기를 전개해나가고 있음을 보여주기 위한
   목적으로 시스템의 출력에 해당 문장을 의도적으로 포함시켰습니다.
   오류가 아니니 놀라지 마시고 참고해주시면 감사하겠습니다:)
```

<br/><br/>

**Comment by Tastypotato245** [comment]
<img width="554" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/5e3b4573-43ce-4b73-ad39-00cdc4f0680f">

회원가입이 안돼요 ㅠㅠ

id : Kyusu12
pw : Kyusu12

로 했습니다

**Comment by suminl22** [comment]
확인 결과, 서버 cors 정책 및 port 충돌로 인해 잠시 서버 통신의 오류가 있었습니다.
현 시각 기준으로 로그인/회원가입 issue 해결되었습니다 :)

**Comment by Tastypotato245** [comment]
<img width="1237" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/6ce5acea-c68a-4288-b059-ac5fd0411456">

헉

<img width="1235" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/9cc72860-4821-4eb1-9ede-2f29fa1be709">


단군신화도 안돼요 ㅠㅠ

<img width="1229" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/c05236c2-1129-4a24-b5b7-a8dcff4d2395">

바나나 먹고싶다는 유치한 대답에도 잘 안되네용

**Comment by suminl22** [comment]
gpt api 호출 관련 이슈 해결했습니다! 현 시각 이후로 정상 서비스 이용 가능합니다:)
![1](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/83565901/702e844b-6c92-4d7f-96b4-1a8a782a79a7)

**Comment by bykbyk0401** [comment]
생각보다 이야기가 잘 만들어지는 것 같아서 재미있었습니다~ 
이야기 완결 기능까지 완료된 모습이 기대됩니다!!

++) 사용해보며 느낀 점을 작성해봤습니다. 앞으로의 개발에 도움이 되면 좋겠습니다:)

<img width="1114" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/d39498f3-f565-4780-9aab-b37163a03d5b">

1. 가끔씩 아이가 이해하기 어려운 단어나, 문장이 등장하는 것 같아 개선된다면 좋을 것 같다고 생각했습니다.
2. '소년'과 '소녀'라는 단어가 문맥과 상관없이 무작위로 등장하는 것 같아, 이야기를 완성할 때 주의가 필요할 것 같습니다.
3. 장미와 가시라는 소재가 등장하자, 뜬금없는 어린왕자 이야기가 등장하여 당황스러울 수 있을 것 같습니다.

감사합니다~

**Comment by yjyoo3312** [comment]
<img width="1086" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/bec52bf6-d717-4eae-89b4-66385729427e">

서비스에 필요한 채팅이 잘 이루어 지는군요! 개언적으로 대화 내용이 약간씩 문맥이 맞지 않는 거 같은데 이부분을 최종 발표까지 더 개선이 가능하다면 매우 재밌게 사용할 수 있을 거 같습니다

**Comment by Jeong-In-Lee** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/80769394/a861b86a-c159-4fed-aa8f-69925c59a8ff)
UI도 깔끔하고, GPT 말투도 아이용으로 귀엽게 바뀐 것이 좋았습니다. 다만 이야기 맥락을 맞지 않게 이끌어가는 점이 조금 아쉽습니다.

**Comment by JHoon0214** [comment]
> <img alt="image" width="1086" src="https://private-user-images.githubusercontent.com/12525981/328930754-bec52bf6-d717-4eae-89b4-66385729427e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDczOTMsIm5iZiI6MTcxNTI0NzA5MywicGF0aCI6Ii8xMjUyNTk4MS8zMjg5MzA3NTQtYmVjNTJiZjYtZDcxNy00ZWFlLTg5YjQtNjYzODU3Mjk0MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5MzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDc5N2Y2N2U1MTNlOTNmMmRiYjU1NGM5NDZlMzcwM2UxMzFjYjc3ZDQwMTg5ZjA2YTVlYTUzOTRiMDZkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sM6C1eBPJV27YwsXjcLWw_js4vESoA5Iz3P9cotRBrs">
> 서비스에 필요한 채팅이 잘 이루어 지는군요! 개언적으로 대화 내용이 약간씩 문맥이 맞지 않는 거 같은데 이부분을 최종 발표까지 더 개선이 가능하다면 매우 재밌게 사용할 수 있을 거 같습니다

======================================

안녕하세요 교수님! 좋은 말씀 감사합니다 :)
현재 주요 기능을 구현해 동작하는 서비스를 배포하는것에 집중하느라 프롬프트 성능은 아직 충분하지 않은 상황입니다.
프롬프트 개선 작업은 데모 기간동안 계속 진행중입니다. 데모 기간이 끝나기 전에 개선된 데모 프롬프트도 선보이겠습니다...!

**Comment by JHoon0214** [comment]
> ![image](https://private-user-images.githubusercontent.com/80769394/329136520-a861b86a-c159-4fed-aa8f-69925c59a8ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDgwOTksIm5iZiI6MTcxNTI0Nzc5OSwicGF0aCI6Ii84MDc2OTM5NC8zMjkxMzY1MjAtYTg2MWI4NmEtYzE1OS00ZmVkLWFhOGYtNjk5MjVjNTlhOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA5NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMGUzMWQ5ZjRjNTIwNzk1NWRjNWY0Y2E1MzJkOWRlZjEwZDUyNGJiODZiODE0Yjg5M2RhNzZhYjMzNTcyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kcVSM3BNfdl9qIaxblyUwvs9d1MW22kLQ5W6kGgxPS4) UI도 깔끔하고, GPT 말투도 아이용으로 귀엽게 바뀐 것이 좋았습니다. 다만 이야기 맥락을 맞지 않게 이끌어가는 점이 조금 아쉽습니다.

=====================================

안녕하세요 정인님. 좋은 피드백 주셔서 감사합니다 :)
정인님 말씀대로 프롬프팅 성능이 만족할만한 수준으로 나오지 않아 현재 개선작업을 진행하고 있습니다.
현재 사용되고 있는 프롬프팅 스크립트는 처음 주제를 선정할때 같이 작성했던 버전으로 이후로 개선 작업을 꾸준히 거쳐 조금은 성능이 향상된 후속 버전들이 있습니다.
1차데모 기간 내에 100프로의 프롬프팅은 하기 어려울 것 같지만 어느정도 만족할 수 있는 수준의 프롬프트를 완성해 데모 기간이 끝나기 전에 업데이트 해보겠습니다
저희 소프트웨어에 관심 가져주셔서 감사합니다!

**Comment by RaccHoon** [comment]
안녕하세요 점검 공지 드립니다~!
현재 저희 서비스의 대부분의 기능은 aws에 배포한 서버에서 제공하지만 일부 API는 ngrok을 이용해 제공하고 있었습니다.
이랬던 API들을 통합해 다시 배포하려고 합니다.
따라서 금일(9일) 오후 7시부터 30분가량 서비스가 중지될 예정입니다. 양해 부탁드립니다ㅜㅜㅜ

**Comment by suminl22** [comment]
안녕하세요 점검 시간이 연장되어 공지 드립니다~!
**금일(9일) 오후 8시**까지 서비스가 중지될 예정입니다!! 양해 부탁드립니다ㅜㅜ
빠르게 복구하도록 하겠습니다!

**Comment by MarcelMaxx** [comment]
너무 재미있네욬ㅋㅋ 잘 동작되었어요! 
<img width="1440" alt="Screenshot 2024-05-10 at 12 29 32 AM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/fa9743c5-0433-40fe-b610-c313823179d2">
'#발단, #1번째 대화'라는 게 나타나는데, 이게 혹시 정상인가요? 

그리고 Safari AutoFill 여는 경우에 회원가입 못하는데요.. 혹시 해결해주셔도 되나요?ㅠㅠ (input field의 길이는 좀 늘리면 될 것 같아요)
<img width="589" alt="Screenshot 2024-05-10 at 12 17 24 AM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/b48eca47-056c-4ffb-86a4-a82ba2642db9">

**Comment by JHoon0214** [comment]
> 너무 재미있네욬ㅋㅋ 잘 동작되었어요! <img alt="Screenshot 2024-05-10 at 12 29 32 AM" width="1440" src="https://private-user-images.githubusercontent.com/127838206/329299462-fa9743c5-0433-40fe-b610-c313823179d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE3MzUsIm5iZiI6MTcxNTMxMTQzNSwicGF0aCI6Ii8xMjc4MzgyMDYvMzI5Mjk5NDYyLWZhOTc0M2M1LTA0MzMtNDBmZS1iNjEwLWMzMTM4MjMxNzlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMzIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTg0ZjVlMTY0MTQ4YjAxYTFmZjhlMjYxMTVhZjRhMmJhZDE0NmVkNWZkMTc3ODE5NzA0YTE4NWExMDYyZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Ob7Cow1q7Bl3nbXDye-qzXxhO4pQj_SrRtCB77D4hY"> '#발단, #1번째 대화'라는 게 나타나는데, 이게 혹시 정상인가요?
> 
> 그리고 Safari AutoFill 여는 경우에 회원가입 못하는데요.. 혹시 해결해주셔도 되나요?ㅠㅠ (input field의 길이는 좀 늘리면 될 것 같아요) <img alt="Screenshot 2024-05-10 at 12 17 24 AM" width="589" src="https://private-user-images.githubusercontent.com/127838206/329294560-b48eca47-056c-4ffb-86a4-a82ba2642db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE3MzUsIm5iZiI6MTcxNTMxMTQzNSwicGF0aCI6Ii8xMjc4MzgyMDYvMzI5Mjk0NTYwLWI0OGVjYTQ3LTA1NmMtNGZmYi04NmE0LWE4MmJhMjY0MmRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMzIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTliNTIyMjRjODg2MjVmZDBhYTQ2ZTVmZjczMzNlMjM4YjkzNWJmZTE4MzVhNDhhZTZlMDg3MzZlODc3ZDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n8FVk5xZrM4rNeiz6gGSdEH9t0xASX8bEl10Wqa3QXE">

==========================

안녕하세요 MarcelMaxx님 아직 많이 부족한 소프트웨어인데 좋게 봐주셔서 감사합니다!
말씀해주신 '#발단, #1번째 대화'는 이번 프롬프팅 업데이트하며 새롭게 추가한 기능입니다.
앞으로 이 기능을 계속 유지할지는 잘 모르겠지만 데모 버전에서 소프트웨어의 동작이 제대로 되고 있는지 확인하기 위한 지표로 확인하고자 추가했습니다.  
#발단-전개-위기-절정-결말까지 이야기가 차근차근 진행된다면 의도한 대로 소프트웨어가 잘 동작한 것이고, 그렇지 못한 경우가 발생한다면 그 상황에 대해 설명과 스크린샷을 남겨 주시면 저희에게 큰 도움이 될 것 같습니다...!  

사파리 환경에서 테스트를 안해봐서 회원가입 이슈가 있는줄 몰랐네요ㅜㅜㅜ  
데모1까지 준비기간이 길지 않았기 때문에 데모데이 전까지 중요한 기능을 모두 개발하기에는 한계가 있었습니다. 
따라서 현재는 저희 소프트웨어의 특징을 보여줄 수 있는 기능을 우선적으로 구현한 상황입니다.  
말씀해주신 부분을 포함하여 여러 문제들은 이번학기 남은 기간동안 다른 기능들을 고치면서 개선해 보겠습니다.  

P.S 아직 저희 소프트웨어가 완전하진 않아 조금 문제가 있지만 그래도 사용자 입력을 동화에 좀더 어울리게 작성하면 이야기의 완성도가 개선될 수 있습니다 :) 저희 소프트웨어에 관심가져 주셔서 감사합니다!

**Comment by MarcelMaxx** [comment]
> > 너무 재미있네욬ㅋㅋ 잘 동작되었어요! <img alt="Screenshot 2024-05-10 at 12 29 32 AM" width="1440" src="https://private-user-images.githubusercontent.com/127838206/329299462-fa9743c5-0433-40fe-b610-c313823179d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE3MzUsIm5iZiI6MTcxNTMxMTQzNSwicGF0aCI6Ii8xMjc4MzgyMDYvMzI5Mjk5NDYyLWZhOTc0M2M1LTA0MzMtNDBmZS1iNjEwLWMzMTM4MjMxNzlkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMzIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTg0ZjVlMTY0MTQ4YjAxYTFmZjhlMjYxMTVhZjRhMmJhZDE0NmVkNWZkMTc3ODE5NzA0YTE4NWExMDYyZmExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Ob7Cow1q7Bl3nbXDye-qzXxhO4pQj_SrRtCB77D4hY"> '#발단, #1번째 대화'라는 게 나타나는데, 이게 혹시 정상인가요?
> > 그리고 Safari AutoFill 여는 경우에 회원가입 못하는데요.. 혹시 해결해주셔도 되나요?ㅠㅠ (input field의 길이는 좀 늘리면 될 것 같아요) <img alt="Screenshot 2024-05-10 at 12 17 24 AM" width="589" src="https://private-user-images.githubusercontent.com/127838206/329294560-b48eca47-056c-4ffb-86a4-a82ba2642db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE3MzUsIm5iZiI6MTcxNTMxMTQzNSwicGF0aCI6Ii8xMjc4MzgyMDYvMzI5Mjk0NTYwLWI0OGVjYTQ3LTA1NmMtNGZmYi04NmE0LWE4MmJhMjY0MmRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQwMzIzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTliNTIyMjRjODg2MjVmZDBhYTQ2ZTVmZjczMzNlMjM4YjkzNWJmZTE4MzVhNDhhZTZlMDg3MzZlODc3ZDQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n8FVk5xZrM4rNeiz6gGSdEH9t0xASX8bEl10Wqa3QXE">
> 
> ==========================
> 
> 안녕하세요 MarcelMaxx님 아직 많이 부족한 소프트웨어인데 좋게 봐주셔서 감사합니다! 말씀해주신 '#발단, #1번째 대화'는 이번 프롬프팅 업데이트하며 새롭게 추가한 기능입니다. 앞으로 이 기능을 계속 유지할지는 잘 모르겠지만 데모 버전에서 소프트웨어의 동작이 제대로 되고 있는지 확인하기 위한 지표로 확인하고자 추가했습니다. #발단-전개-위기-절정-결말까지 이야기가 차근차근 진행된다면 의도한 대로 소프트웨어가 잘 동작한 것이고, 그렇지 못한 경우가 발생한다면 그 상황에 대해 설명과 스크린샷을 남겨 주시면 저희에게 큰 도움이 될 것 같습니다...!
> 
> 사파리 환경에서 테스트를 안해봐서 회원가입 이슈가 있는줄 몰랐네요ㅜㅜㅜ 데모1까지 준비기간이 길지 않았기 때문에 데모데이 전까지 중요한 기능을 모두 개발하기에는 한계가 있었습니다. 따라서 현재는 저희 소프트웨어의 특징을 보여줄 수 있는 기능을 우선적으로 구현한 상황입니다. 말씀해주신 부분을 포함하여 여러 문제들은 이번학기 남은 기간동안 다른 기능들을 고치면서 개선해 보겠습니다.
> 
> P.S 아직 저희 소프트웨어가 완전하진 않아 조금 문제가 있지만 그래도 사용자 입력을 동화에 좀더 어울리게 작성하면 이야기의 완성도가 개선될 수 있습니다 :) 저희 소프트웨어에 관심가져 주셔서 감사합니다!

아, 그래서였군요.. 정말 꼼꼼하시네요ㅎㅎ 답변해 주셔서 감사 드리고 더 보완된 버전 기대합니다!
