### ISSUE TITLE
[demo1][19조]recipe service

### ISSUE THREAD

**Issue by jeungchanwoo** [PiLab-CAU/OpenSourceProject-2401#22]
### 데모링크

> https://chanwoo-oss-19.web.app/

###  사용방법

> 
1. 검색창에 식재료를 검색한다
2. 검색어를 포함한 재료가 노출된다
3. 원하는 재료를 선택한다
4. '레시피 만들기' 버튼을 누르고 기다린다
5. alert를 통해 결과를 받는다

**Comment by Tastypotato245** [comment]
<img width="637" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/2c7050d7-96dc-429f-91ec-ce82b44e7d70">

아직 검색이 잘 안되는 것 같습니다!

<img width="755" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/2fb878fd-9791-431b-af2c-7c576b5b2852">

혹시 몰라 egg로 검색도 해봤습니당

**Comment by yjyoo3312** [comment]
<img width="1184" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/884c4b8e-7d98-4a72-b88d-d53992409621">
<img width="408" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/ba8b475f-31c3-4e3c-af86-96311f4195b5">

재료들 선택하여서 요리들 만들어 보았는데, 될법한 요리가 잘 나오네요 

여기에 추가로 생각하시는, 혹은 업데이트 계획 중이신 기능이 있으실까요?

**Comment by randy0119** [comment]
안녕하세요? 기능 동작 잘 확인했습니다.
다름이 아니라 결과를 받고 궁금한 점이 생겨 문의드립니다.

'파프리카', '닭고기', '과일 식초'를 입력하고 다음과 같은 결과를 받았습니다...
![Untitled](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/9418cc8c-c06f-44e9-a733-8505c6aa4cdf)

'마약물'이라는 워드가 할루시네이션인지는 몰라도 레시피 결과에 포함되었습니다.
초기 버전이라 유해성 검열이 잘 안 이루어질 수도 있다고 생각하나,
혹시나 할루시네이션 대비 및 유해성 검열 정책에 대해 추후 진전 계획 있는지 문의드리고 싶습니다...!

**Comment by shu030929** [comment]
<img width="1037" alt="스크린샷 2024-05-09 오후 2 27 49" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/166142544/2fcc86a0-81ab-4b4a-9727-9175b6bb0f3e">
"블루 치즈"를 검색했을때, 식재료가 아닌 특정 브랜드의 블루치즈를 추천해줍니다. 
달걀, 당근,소금 등등과 같은 흔한 재료들을 선택하면 좋은 레시피를 제공해주는 것 같습니다!

**Comment by JHoon0214** [comment]
<img width="1045" alt="Pasted Graphic 3" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/73931440/2ad6fb0a-4356-482d-885b-2157a75ffc1c">

제가 집에서 자주 만들어먹는 삼겹살 덮밥 재료를 넣어봤는데 비슷한 음식 레시피를 추천해 줘서 놀랐습니다
자취 초보인 저에게 아주 안성맞춤인 소프트웨어네요 :)  

<img width="429" alt="chanwoo-osS-19 web app 내용" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/73931440/9257ffe3-b997-46cb-8e4c-b5b298aca028">  

5번에서 담고에서 담 대신에 한자가 나왔습니다. 아마 GPT 문제인거 같아요...!

**Comment by MarcelMaxx** [comment]
너무 좋고 재미있는 아이디어가 이네요! 지피티는 상상력이 뛰어나네 ㅋㅋㅋ
<img width="819" alt="Screenshot 2024-05-09 at 11 14 30 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/18234b78-c21b-45d2-9582-02b23d56f801">
근데 위에 사진에서 '밀가루'를 검색했는데, 재료 목록에 나타나지 않았어요. 혹시 이건 정상적인 건가요?

그리고 검색 못하는 재료가 좀 많은 것 같은데요.
<img width="966" alt="Screenshot 2024-05-09 at 10 52 13 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/aef977ad-fa6f-4c1d-8869-f12f67203732">
<img width="1051" alt="Screenshot 2024-05-09 at 11 09 53 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/b0d96660-55d1-4c39-9feb-7ba322dce5f8">

궁금해서 혹시 선택 가능한 재료 데이터가 어떻게 받으셨나요? 그냥 직접 입력하고 ChatGPT한테 보내면 안 되는 건가요?

**Comment by LUCETE012** [comment]
5조 김여진입니다 ☘️

검색이 잘 되지 않는 재료들이 있는 것 같습니다 !
<img width="1428" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/84865066/865e835e-b0b8-49af-ac39-5c9668db8e9e">

검색한 식재료와 크게 관련이 없는 키워드들이 뜹니다 ! 
<img width="1404" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/84865066/a4bda241-ded0-4541-95dc-09b3a6ffaab2">

결과 내용이 팝업이 아닌 새로운 창에서 뜨면 더 좋을 것 같습니다 !
<img width="423" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/84865066/6e3b7d0c-9e68-4004-b384-e7865bf23fb5">

**Comment by ahnavocado** [comment]
<img width="1435" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/66175689/992452c0-6ea7-4f9a-847b-55a7bc4c31f9">
데모 버전 너무 잘 보았습니다!
다만 궁금한점이 있습니다. 물 이라는 검색어를 검색 하였더니 물장군 이라는 연관 검색어가 떠서 이용해보았습니다. 이때 응답이 물장군이 마늘장아찌라는 응답과, 이를 이용하는 요리가 아닌 만드는 법을 출력 받았습니다. 
이런 점에서 어디서 재료를 검색하는지, 재료를 이용한 요리가 아닌 재료에 대한 요리법이 출력 되는 것이 정상적인 동작인지 여쭤보고 싶습니다
감사합니다 고생하셨습니다

**Comment by sanghunmoon** [comment]
9조 문상헌입니다!
재밌는 제품 잘 써봤습니다 🙇‍♂️ 
레시피가 꽤나 명확하게 작성이 되고, 요리도 딱 해볼만한 정도로 추천해줘서 좋았습니다 👍 
식재료를 검색하는 것이 어려워서 일단 검색된 재료들로 했는데, 재료 선택 경험을 좀 더 개선하면 더욱 좋은 서비스가 될 것 같아요!
그래도 검색된 재료가 있어서 테스트 하는 것은 매우 용이했는데, 테스트하면서 정말 좋은 아이디어라고 느꼈습니다 ㅎㅎ
남은 학기 동안에도 화이팅입니다!

<img width="445" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/40769396/a96c8217-4797-4714-8ce8-6b67b721279f">
