### ISSUE TITLE
[demo1][14조] cautry

### ISSUE THREAD

**Issue by yongsoocho** [PiLab-CAU/OpenSourceProject-2401#23]
## 데모 링크:
기존 : <s>[https://67214c8a.2024-oss-team14.pages.dev/dashboard</s>

5/19부터 변경 : https://2024-oss-team14.pages.dev/dashboard

## 사용 설명
아직 UI만 구성되었기 때문에 차후에 애플리케이션 로직을 추가할 예정입니다.

## 최종 목표 대비, 현재까지 구현된 사항
- [x] UI
- [x] 백엔드 템플릿 작성 (아직 로직 구현 X)
- [x] 프론트 템플릿 작성 (아직 연결 X)

## To be
- [ ] Chat GPT 연결
- [ ] 에러 아카이빙 및 검색 로직 구현
- [ ] Feed back 받을 수 있고 간단한 코드 테스트 할 수 있도록 구현

**Comment by Tastypotato245** [comment]
추가 되면 즐기러 와보겠습니다!! (다른 조에는 다 comment를 남겨서 여기도 남깁니다 ㅎㅎ )

 +UI가 이뻐요 부러워요 ㅜㅜ 

<img width="1641" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/e5f5ac91-b044-4b1d-ac90-0f03f8739f29">

**Comment by yjyoo3312** [comment]
네, 페이지 접속 잘 된 것 확인하였습니다. 기능 추가 되는대로 저도 다시 테스트 해보겠습니다:)

**Comment by Bowoon1216** [comment]
안녕하세요~ 테스트 겸 들렸습니다 :)
검색 창과 버튼 디자인이 트랜디해보여서 탐나네요 ㅎㅎ 😄 
추후에 기능이 추가된 cautry도 기대하겠습니다!!

**Comment by LUCETE012** [comment]
5조 김여진입니다☘️

UI가 심플하고 예쁘네요 !!! 
기능들이 정말 기대가 됩니다 😊
