### ISSUE TITLE
[demo1][15조] 자소서친구

### ISSUE THREAD

**Issue by lois505** [PiLab-CAU/OpenSourceProject-2401#24]
# 데모링크:
---
https://4429-59-187-196-57.ngrok-free.app
# 사용설명:
---
윗빈칸에 자소서의 질문 한가지를 입력하고 밑빈칸에 해당하는 질문에 적을 키워드를 적습니다. 결과로 프로그램이 어떤 키워드가 더 들어가면 좋을지를 출력해줍니다.

**Comment by Tastypotato245** [comment]
<img width="761" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/5c82fdf3-9d37-4434-8abf-c42e002eb4ba">

이전 발표에서 큰 프레임을 제공하고, 그것을 사용자 인풋 기반으로 적절히 채울 수 있도록 도와준다고 하셨던 것이 기억에 남습니다! 이번 데모에서는 혹시 더 업그레이드 되는 내용이 있나요?

**Comment by lois505** [comment]
죄송합니다. 웹크롤링에 애를 먹고 있는 상황이라 발표때 말씀드린 기능을 아직 구현하지 못해서 당장은 업그레이드 된 부분이 없습니다 :(
감사합니다

2024년 5월 8일 (수) 오전 1:12, LEE KYUSUNG ***@***.***>님이 작성:

**Comment by yjyoo3312** [comment]
<img width="1210" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/a60a865c-65b5-4b3b-aaef-e0ace0b7b864">

네, 웹페이지 접속 및 테스트 가능한 부분 확인하였습니다:) 최종 발표 때 저 outline을 기반으로 좀 더 자세한 자소서의 내용이 추가 되는 것일까요?

**Comment by lois505** [comment]
넵 현재 크롤링 완료해서 합격자소서 키워드 추출까지 완료한걸로 새로 배포합니다 :) 최종발표때는 합격자소서의 키워드를 기반으로 자소서의 틀을 잡아주는것으로 목표를 두고 있습니다.

**Comment by leesuji2000** [comment]
현재 서버가 닫혀있어서 사용할 수가 없습니다.ㅜ

**Comment by lois505** [comment]
죄송합니다 복구했습니다!

2024년 5월 9일 (목) 오후 1:56, SUJI ***@***.***>님이 작성:

**Comment by JHoon0214** [comment]
<img width="1493" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/73931440/2ca69f25-7a7b-46f4-b6c4-694cecaf1e9e">

자소서와 관련된 키워드가 잘 나오네요!
예시가 같이 있으면 좀더 쉽게 이용할 수 있을 것 같습니다.  
자소서를 써야 하는 시즌이 오면 도움이 많이 될 것 같아요 :)

**Comment by MarcelMaxx** [comment]
링크 열수 없네요ㅠㅠㅜ
<img width="703" alt="Screenshot 2024-05-09 at 10 15 01 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/bb096a93-9749-4808-9e7c-3a2e6dd0bdac">

**Comment by MarcelMaxx** [comment]
나중에 네이버에서 이 프로젝트를 찾을 수 있다면, 저는 꼭 이것으로 자소서를 쓸 거에요! ㅋㅋㅋ 너무 재미있어요!
<img width="221" alt="Screenshot 2024-05-09 at 10 21 08 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/de8657a1-b8da-4578-b092-f093206a6677">

자기소개서 뿐만 아니라, 거의 모든 곳에서 사용할 수 있어요! 왜냐하면 이 걸 통해 더 많은 아이디어를 얻을 수 있거든요!
<img width="598" alt="Screenshot 2024-05-09 at 10 21 41 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/a0112c98-c469-40e3-b4c1-8d402bf64ffa">

곧 더 보완한 기능이 나올 걸 기대해요!

**Comment by MarcelMaxx** [comment]
나중에 네이버에서 이 프로젝트를 찾을 수 있다면, 저는 꼭 이것으로 자기소개서를 쓸 거에요! ㅋㅋㅋ 너무 재미있어요!
<img width="1182" alt="Screenshot 2024-05-09 at 10 21 47 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/9cca5275-e6ea-4490-94fc-e1ab0b7f95a0">

자기소개서 뿐만 아니라, 거의 모든 곳에서 사용할 수 있어요! 왜냐하면 이 걸 통해 더 많은 아이디어를 얻을 수 있거든요!
<img width="598" alt="Screenshot 2024-05-09 at 10 21 41 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/b0cbd856-d84f-4a8f-8825-f3edb7a63cf5">


곧 더 보완한 기능이 나올 걸 기대해요!

**Comment by MarcelMaxx** [comment]
나중에 네이버에서 이 프로젝트를 찾을 수 있다면, 저는 꼭 이것으로 자소서를 쓸 거에요! ㅋㅋㅋ 너무 재미있어요!
<img width="1182" alt="Screenshot 2024-05-09 at 10 21 47 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/5d804d6a-24f3-4d99-aafa-24ef62369f42">

자기소개서 뿐만 아니라, 거의 모든 곳에서 사용할 수 있어요! 왜냐하면 이 걸 통해 더 많은 아이디어를 얻을 수 있거든요!
<img width="1190" alt="Screenshot 2024-05-09 at 10 29 15 PM" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/127838206/23ed4150-4da2-43df-abc8-8c37d8ee6abd">

곧 더 보완한 기능이 나올 걸 기대해요!

**Comment by LUCETE012** [comment]
5조 김여진입니다☘️

항목과 키워드에 어떤것을 입력해야할 지 감이 잘 오지 않아서, 예시가 있으면 좀 더 구체적으로 입력할 수 있을 것 같습니다.
그리고 입력 결과가 좀 더 가독성있게 보여지면 좋을 것 같습니다 !

입력한 키워드에 대해 전체적은 플로우를 말해주는 것이 도움이 많이 될 것 같습니다. 챗봇과의 소통을 통해 내용을 수정해 나갈 수 있으면 더 좋을 것 같습니다 !
