### ISSUE TITLE
[demo1][13조] ChatDa

### ISSUE THREAD

**Issue by ParkJh38** [PiLab-CAU/OpenSourceProject-2401#25]
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/6e3fbecc-573f-4ca2-acbc-d82bd2713937" width="40%">

### [데모 링크]
http://43.202.126.252:8080/
---

### ※  [업데이트] ChatDa가 작성해준 일기의 문체가 자연스럽게 변경되었습니다!! 
---

### [사용 설명]
ChatDa 서비스 이용 방법은 다음과 같습니다.

0. 메인 페이지에 접속하면 이름을 입력하고 대화를 시작할 수 있습니다.
1. 대화를 마치고 지금까지의 대화 내역을 바탕으로 생성된 일기를 확인할 수 있습니다.
2. 대화는 유저가 종료 버튼을 누르거나 일정 길이 이상으로 대화 기록이 쌓이면 종료됩니다.

3. 메인 페이지에서 캘린더 링크에 접속하여 일기가 저장될 캘린더 페이지를 확인할 수 있습니다.

아래의 예시 사진을 참고해 주세요!
---

### [예시 사진]
**0. 메인 화면**
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/18ca6bac-7c84-4430-b06d-13f5848e7006" width="60%">

- 이번 Demo에서는 로그인을 하지 않아도 이름 빈칸에 이름을 입력하면 챗다와 바로 대화를 할 수 있습니다.

- 로그인 기능은 추후 추가될 예정입니다 :) 
---

**1. ChatDa 대화 화면**
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/30b867d6-872e-4a64-b26b-661484e9e55a" width="100%">

---
**2. 데모 버전 대화 제한**

<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/760d0763-8831-4c7f-a241-a4d6a1c44536" width="50%">

- 데모 버전에서는 최대 3개의 화제에 대해 10회 정도의 채팅으로 구성되어있습니다.
- 현 버전은 초기 버전으로 최종 구현에서는 더 다양한 화제에 대해 긴 대화를 나눌 것 입니다.
- 또한 사용자 특화된 대화는 생성되지 않습니다.

---
**3. 일기 생성**
- 챗다와의 대화를 마친 후 일기 생성을 하기 위해서는 오른쪽의 **[대화를 마치고 일기 생성하기]** 버튼을 누르면 됩니다! 
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/b089d23e-8d45-4402-b74a-7ccf457b5994" width="50%">

- **"일기를 작성중입니다. 잠시만 기다려 주세요(30~40초)"** 문구의 팝업이 뜨면 [**확인**]을 누르고 30초 정도 기다려 주세요!
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/062a84ba-e1fb-4ab8-b3de-1024ec08865c" width="50%">

- 아래는 챗다와의 대화 후 생성된 일기의 예시입니다. 
- ~~일기의 문체와 문장 간의 연결 부분의 부자연스러움은 아직 보완이 필요해 보이며, 이는 추후에 보완될 예정입니다.~~

<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/07419fce-578e-41c2-80ba-87e2d7035d57" width="95%">

---
**4. 일기 조회**

<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/b1cdb950-a44d-438a-a1ad-6c105d3dae4a" width="50%">

- **[Diary]** 버튼을 누르면 캘린더 페이지로 이동합니다! 

<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/f55fea84-1ff5-4d00-84f8-c2344a7f04b7" width="80%">

- 아직은 캘린더에서 챗다와의 대화를 통해 생성된 일기를 조회할 수 **없습니다**!!! 
- 생성된 일기 조회는 로그인 기능이 추가된 이후에 가능합니다!

- Demo 캘린더에서 날짜 옆에 위치한 이모지를 클릭하면 예시 일기를 확인할 수 있습니다.
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/e0d05379-a016-4005-8154-1dd2ee166266" width="100%">
<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/6ebc3841-fe1e-4b5a-b441-eb456b022a8a" width="100%">

---
### 구현 상황
챗다 대화 알고리즘 ver1을 적용하였습니다.

생성된 일기는 대화 종료 후 확인 할 수 있으며 이후 다시 확인하는 기능은 현재 구현하지 않았습니다.

최종 버전에서는 캘린더 페이지에서 사용자 별로 자신이 작성한 일기를 모두 확인 할 수 있습니다.

**Comment by Bowoon1216** [comment]
안녕하세요~
대화가 생각보다 잘 통해서 놀랐습니다 😄 테스트하려 했다가 챗다와 수다 떨었습니다 ㅎㅎ
다만 아직 개발 초기라 그런지, 대화흐름이 부자연스러울 때도 있고 맥락이 맞지 않는 상황도 있었습니다..! 😢 

더해서 챗다와 일기를 만들어보며 느꼈던 점들을 도움이 되고자 말씀드립니다
일기에도 대화 내용이 잘 담기지만, 대화흐름에 맞지 않는 이야기까지도 넣어서 일기라는 느낌이 들지 않았습니다..
일기 형식에서는 아래 사진과 같이 제 3자의 입장에서 서술하듯이 어색한 느낌이 들었습니다
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/105543811/5c1b7020-598e-429c-af6e-e8cbbf376702)

추후에 더욱 업데이트된 챗다 기대하겠습니다! 😄

**Comment by ParkJh38** [comment]
안녕하세요~ 피드백 감사드립니다 :)
챗다와의 대화 부분에서는 저희가 프롬프트를 통해 적절한 타이밍에 화제를 전환할 수 있도록 하여 최대한 자연스럽게 구현하고자 했습니다! 
하지만 말씀해주신대로 아직은 했던 질문을 비슷하게 똑같이 한다던지, 갑자기 한참전의 대화 화제를 갖고 오는 등의 부자연스러운 상황이 발생합니다.. 아직 챗다 대화 알고리즘  ver1 이라는점 감안하여 해주시면 감사하겠습니다!!

대화를 바탕으로 일기를 생성하는 부분에서는 아직 문체가 제3자의 입장에서 서술이 되고 있어 부자연스러운 부분이 존재하며, 맥락에 맞지 않는 부분이 중간에 들어가기도 하여 어색한 부분이 다소 존재합니다. 이 부분도 추후 자연스럽게 생성되도록 업데이트 예정이니 기대해주세요 :)

**Comment by yjyoo3312** [comment]
생각보다 대화가 잘 이어지는 것이 흥미롭네요, 개인적으로 약간 조사나 어투가 안 맞는 부분은 나중에 유저가 직접 수정할 수 있어도 편리할 거 같습니다:)

**Comment by skwent77** [comment]
<img width="685" alt="chatDa" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/46518769/2758205b-d1dc-4395-93a1-46c8a841e2ed">

안녕하세요.
 chatDa 프로젝트 엄청 인상 깊었어서 왜 없나 생각하고 있었습니다. 
완성도가 너무 높으신 것 같아요.
일기 생성도 GPT API임을 감안하면 속도가 느리지 않네요.
재밌게 사용했습니다! 
9조 대표로 리뷰 남깁니다.

**Comment by ParkJh38** [comment]
@yjyoo3312 피드백 감사합니다 교수님! 
현재 챗다가 일기를 작성해주는 부분에서 조사나 어투등 문체가 다소 어색한점이 있어 프롬프트를 보완할 예정입니다!
또한 작성해준 일기를 유저가 직접 수정한 뒤에 저장할 수 있는 기능도 추가할 예정입니다 :) 감사합니다.

**Comment by ParkJh38** [comment]
@skwent77 코멘트 감사합니다!
챗다와의 대화가 만족스러우셨다니 다행입니다 :)
가끔 대화의 흐름이 부자연스러운 부분이 존재하지만 여러 버전의 프롬프트를 통해 보완할 예정입니다!

**Comment by bykbyk0401** [comment]
현재 대화 한문장을 입력하고나면 아무 변화가 없는 상태로 멈추는 것 같습니다..
다시 들어가서 반복해봐도 마찬가지이고, '대화를 마치고 일기 생성하기'를 눌러봐도 멈춤 현상이 있는 것 같습니다.

한번 확인 부탁드려요!!

**Comment by ParkJh38** [comment]
@bykbyk0401 
현재 서버에 문제가 발생한 것으로 확인되어 조치 중에 있습니다..!

**Comment by ParkJh38** [comment]
### 서버 정상 복구되었습니다!

![240509 server_error_detected](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/3f7d0db6-ff73-436f-b02a-a16975a2b95b)

확인해보니, 테스트 과정에서 Api 사용시 청구되는 요금의 한도를 설정했었는데 한도가 초과되면서 서버 에러가 발생하였습니다. 

이에 따라 요금 한도 제한을 변경하였으며, 추가적으로 GPT-4에서 GPT-4 Turbo로 변경 조치 했습니다. 
서비스 정상 복구 되었음을 확인하였으니 다시 시도해주시면 감사하겠습니다 :)

<img src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/74255823/31029ff6-7526-4e5d-a02f-300618888c96" width="50%">

**Comment by JHoon0214** [comment]
일기인데 친구랑 대화하는 것 같고 재밌어요!
<img width="315" alt="당연히 롤이지  나는 네임드 롤" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/73931440/f63e0d2a-6900-46a9-8fcb-6a6fe9174bdd">

일기 제목도 자동으로 지어주고 정말 신기하네요
좋은 소프트웨어 잘 보고 갑니다~~!!

**Comment by ParkJh38** [comment]
@RaccHoon 
서비스 사용 리뷰 감사합니다!! 
더 나은 서비스를 위해 준비중이니 기대해주세요 :)

**Comment by LUCETE012** [comment]
5조 김여진입니다☘️

일기 내용을 바탕으로 제목을 만들어주는 것이 좋았습니다 ! 
대충 대답을 해도 공감과 질문을 적절히 잘 섞어서 대답해줘서 감동받았습니다 .. 
<img width="314" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/84865066/bd4639e9-2a17-4ff7-aa53-5499a66d6023">

하루의 일과뿐만 아니라 특정 화제에 대한 질문을 던져줘서 좋은 것도 있지만 최근 영화와 같은 질문은 오늘 일기와는 좀 동떨어지는 듯한 느낌을 받았습니다 ..! 
일기를 생성한 후 수정할 수 있는 기능도 있으면 좋을 것 같아😊

**Comment by ParkJh38** [comment]
@LUCETE012 
서비스 테스트 리뷰 감사합니다!!
말씀해주신대로 일기는 하루의 내용을 기록하는 것인데, 이와 조금 동떨어진 화제를 가져오는 부분에 대해서는 추후 프롬프트 수정될 예정입니다 :)
일기를 수정할 수 있는 기능 또한 추가될 예정이니 기대해주세요 !!

**Comment by Just-love-myself** [comment]
안녕하세요 team 11, 김도균입니다!
제게 부족한 감성 가득 담은 문체로 글을 작성해주는 것 같아 정말 만족스러운 일기가 나왔던 것 같아요!
앞으로도 기대되는 서비스인 것 같습니다. 고생하셨고 화이팅하세요!

**Comment by ParkJh38** [comment]
@Just-love-myself 
서비스 리뷰 감사합니다~
챗다의 더 나은 서비스를 위해 노력하겠습니다! 감사합니다 :)
