### ISSUE TITLE
[협업 요청] 안녕하세요 TEAM01 팀장 이규성입니다.

### ISSUE THREAD

**Issue by Tastypotato245** [PiLab-CAU/OpenSourceProject-2401#26]
# 협업 요청 개요
 안녕하세요 오픈소스SW프로젝트 수강생 여러분, 저는 TEAM1의 팀장 이규성입니다!!

다름이 아니라, 좋은 서비스를 만드는 데 정말 다들 고생이 많으신 와중에, 한 가지 건의 드릴 것이 있어 글을 남깁니다.

평범한 학부생활을 하다보면, 외부에서 지원하는 프레임워크, 라이브러리, API를 사용하는 방법에 대해 아무래도 익숙하지 않은 것이 사실일 겁니다.

## 시행착오들

저희 팀은 Google Login API, OAuth2를 서비스에 붙이는 데 굉장히 오랜 시간을 소모했습니다.

또 다른 팀은, 통신사 Router 설정 때문에 서버 연결이 불안정 했고,

또 다른 팀은 웹 브라우저의 정책인 CORS 때문에 오류를 경험하신 적이 있으실 겁니다.

또, http와 https의 단 한 글자 차이 때문에 인증서 발급이나 도메인 구매 등 골치아픈 상황에 많이들 직면하실 것이라고 생각합니다.

물론 굉장히 잘 하시는 선배님들도 계시고, 혼자서 공식 문서나 Stackoverflow를 보며 잘 해내는 학우분들도 존재하지만,

## 결론

제 개인적으로 최고의 선생님은 **같이 공부하는 동료라고 생각합니다.**

따라서, 이러한 시행착오들에 대해 정리하고, 공유하는 장이 있다면 좋을 것 같습니다.

@yjyoo3312  유영준 교수님께서 허락해주신다면, 해당 이슈 페이지를 시행착오의 발생과 그것의 해결 (Trouble Shooting)을 코멘트로 남기고, 서로에게 도움을 받는 공간으로 활용하고 싶습니다.

앞으로 남은 기간에 개발의 효율도 증가할 것이라 기대하고 있구요.

의견 남겨주시면 감사드리겠습니다 교수님!

추가적으로, 해당 이슈 페이지가 활성화 되지 않더라도, Google OAuth을 통한 로그인 구현 관련은 언제든 도움 드릴 수 있습니다. 혹시 이 이슈 페이지를 사용하지 못하게 된다면, 저희 Sea Turtle demo1 페이지로 오셔서 코멘트 남겨주셔도 됩니다! 정리한 글 공유드리겠습니다.

감사합니다.

**Comment by MarcelMaxx** [comment]
동의합니다

**Comment by yjyoo3312** [comment]
@Tastypotato245 규성님 좋은 의견 감사합니다:) 해당 이슈 페이지를 활용하셔서 서로 적극적으로 구현의 어려웠던 점들 혹은 Trouble shooting 관련한 내용들 공유 및 해결 하시길 권장합니다.

**Comment by rocknroll17** [comment]
좋은 생각이에요 규성님!

**Comment by kimseongsun** [comment]
좋은 생각 같아요

**Comment by Tastypotato245** [comment]
다들 감사드립니다!! 

오늘 Google OAuth 관련 트러블 슈팅 영상으로 간단히 설명드리는 것 올려드릴게용

다들 로그인 기능 구현하시느라 고생이 많으십니다

화이팅입니다!

**Comment by minseok128** [comment]
5조 DearMe 구글 로그인 OAuth 부분도 규성님께 많은 도움 받았는데, 정말 좋은 아이디어 같아요!👍

**Comment by Tastypotato245** [comment]
이곳에서 편하게 팀 프로젝트 중 생긴 어려움이나 해결 방법에 대해 공유해주시면 될 것 같습니다!! 다들 고생 많으셔요~~

**Comment by Tastypotato245** [comment]
# Google OAuth와 FastAPI 연동

영상으로 찍어서 올리고 싶었는데, 시간이 안되겠네요.
제가 개발하는 데 참고한 영상 올립니다.

https://youtu.be/5h63AfcVerM

일단 이 영상을 그대로 따라해서, 로컬 환경에서 Google OAuth를 이용한 로그인 기능을 곧바로 구현할 수 있었습니다.
이후 이를 localhost환경이 아닌, WAN에서 접속할 수 있도록 다음과 같은 키워드들을 중심으로 개발을 진행했습니다.

1. 도메인 구매 (https:// ~ )
2. 원본 서버와 도메인 서버 간의 인증서 설정
3. uvicorn 실행옵션 변경  (저희 프로젝트 의 scrum01 login1 branch를 참고해주세요) (인증서를 포함하여 열기)
4. middleware 옵션 변경 (https_only = True, max_age = 3600)
5. 세션 정보 저장 및 검증 코드 추가
6. 신규 Google API OAuth 클라이언트 생성(**리디렉션** 설정 반드시 확인)과 client id, secret 환경 변수 설정 (.env 파일을 통한)
7. 홈서버 공유기 포트포워딩
8. 홈서버(ubuntu server 22)에서 해당 프로젝트를 daemon service로 등록하여, 자동으로 서비스가 실행되도록 설정
9. 방화벽 설정 (ufw)

개발 해보시다가 막히는 부분이 있을 때 언제든 멘션하시고 코멘트 남기셔도 됩니다!!
