### ISSUE TITLE
[demo1][0조] 프로젝트 제목

### ISSUE THREAD

**Issue by yjyoo3312** [PiLab-CAU/OpenSourceProject-2401#5]
## 데모 링크:
link  적어주세요

## 사용 설명
데모 link  들어가서 어떻게 하면 되는지 자세히 적어주세요~

**Comment by WickedFoxes** [comment]
# 데모 링크
http://ec2-54-180-117-0.ap-northeast-2.compute.amazonaws.com/auth/login/

# 사용 설명
## 사용 전 참고사항
- 뒤로가기(alt + <-  또는 Backspace)는 최대한 사용하지 말아주세요
문제 생성 페이지 기록이 남아, 문제를 다시 생성하는 등의 오류가 생길 수 있습니다.
- 한국어 문서나 영어문서 상관없지만, 토큰을 아끼기 위해 영어로 작성된 자료를 업로드 하시는 것을 추천 드립니다.(Wikipedia 등)
만약 테스트 자료가 따로 필요하시다면 메일을  통해 전달드리겠습니다.

## 회원 가입
- SIGN UP에 접속 후, 회원가입

## 파일 업로드
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/fc3555b7-5b05-4121-ba50-4f7b44d9fd9a)
- Upload New File 버튼을 클릭 

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/3b13f21d-9349-4fd2-9f78-f6e1f36df8bd)
- 제목을 작성하고, 업로드할 수업자료 파일 선택
- 문서의 텍스트는 2500토큰까지 지원
- 문서의 용량은 5MB까지 지원함
- 문서의 유형은 png, jpg, ppt, pptx, doc, docx, pdf, txt, html를 지원함
- save 버튼을 클릭하고 대기
- 조건을 만족하지 못할 경우 어떤 이유로 파일의 내용을 업로드하지 못했는지 안내함
- 문서의 내용이 수업자료를 만들기에 적합하지 않으면, 어떤 내용이 문제가 되는지 안내함
(글의 명확성, 폭력성, xss 공격, 프롬프트 공격 등을 판단)


## 문제 생성
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/627cddb4-34ca-4f25-883c-3fd0a12be844)
- 문서 선택

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/dc3e809b-9cd7-45fb-94d9-367fa5187fe5)
- Create Test 버튼을 클릭
- 원하는 유형의 문제 생성 버튼을 클릭 후 대기

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/47acdbb0-abfa-4cc6-9cb0-1eacb0d5987d)
- 문제가 생성된 것을 확인
- 버튼을 한 번 누르면, 문제가 3개 생성됨

## 문제 삭제
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/39274855-c1e7-473d-b2e0-bf4ca2c716b0)
- 삭제 버튼을 클릭
- 추천 버튼은 기능이 구현되지 않음.
