### ISSUE TITLE
[demo1][16조] ExamGPT

### ISSUE THREAD

**Issue by WickedFoxes** [PiLab-CAU/OpenSourceProject-2401#7]
# 데모 링크
http://ec2-54-180-117-0.ap-northeast-2.compute.amazonaws.com/auth/login/

# 사용 설명
## 사용 전 참고사항
- 뒤로가기(alt + <-  또는 Backspace)는 최대한 사용하지 말아주세요
문제 생성 페이지 기록이 남아, 문제를 다시 생성하는 등의 오류가 생길 수 있습니다.
- 한국어 문서나 영어문서 상관없지만, 토큰을 아끼기 위해 영어로 작성된 자료를 업로드 하시는 것을 추천 드립니다.(Wikipedia 등)
만약 테스트 자료가 따로 필요하시다면 메일을  통해 전달드리겠습니다.

## 회원 가입
- SIGN UP에 접속 후, 회원가입

## 파일 업로드
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/fc3555b7-5b05-4121-ba50-4f7b44d9fd9a)
- Upload New File 버튼을 클릭 

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/3b13f21d-9349-4fd2-9f78-f6e1f36df8bd)
- 제목을 작성하고, 업로드할 수업자료 파일 선택
- 문서의 텍스트는 2500토큰까지 지원
- 문서의 용량은 5MB까지 지원함
- 문서의 유형은 png, jpg, ppt, pptx, doc, docx, pdf, txt, html를 지원함
- save 버튼을 클릭하고 대기
- 조건을 만족하지 못할 경우 어떤 이유로 파일의 내용을 업로드하지 못했는지 안내함
- 문서의 내용이 수업자료를 만들기에 적합하지 않으면, 어떤 내용이 문제가 되는지 안내함
(글의 명확성, 폭력성, xss 공격, 프롬프트 공격 등을 판단)

## 문제 생성
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/627cddb4-34ca-4f25-883c-3fd0a12be844)
- 문서 선택

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/dc3e809b-9cd7-45fb-94d9-367fa5187fe5)
- Create Test 버튼을 클릭
- 원하는 유형의 문제 생성 버튼을 클릭 후 대기

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/47acdbb0-abfa-4cc6-9cb0-1eacb0d5987d)
- 문제가 생성된 것을 확인
- 버튼을 한 번 누르면, 문제가 3개 생성됨

## 문제 삭제
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/39274855-c1e7-473d-b2e0-bf4ca2c716b0)
- 삭제 버튼을 클릭
- 추천 버튼은 기능이 구현되지 않음.

**Comment by Tastypotato245** [comment]
<img width="662" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/48f2a040-4415-4da7-9279-da5f3c776203">

docx가 지원이 안되네요!! 명시해주신 내용과 달라 코멘트 남깁니다!!

<img width="1000" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/7b6b27c1-0bcd-4c0a-b3df-0661022a0ff1">


그리고 간단한 텍스트 한 줄만 나왔는데 굉장한 문제가 튀어나왔네요. 되게 좋은 것 같아요!! 다만 조금만 파일이 커져도 토큰 수 초과했다고 떠서 테스트 케이스 만드는 게 좀 어려웠습니다. 혹시 토큰 수 제한은 2500이 한계인가요?

**Comment by WickedFoxes** [comment]
> <img alt="image" width="662" src="https://private-user-images.githubusercontent.com/63251068/328585283-48f2a040-4415-4da7-9279-da5f3c776203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjcwMTIsIm5iZiI6MTcxNTEyNjcxMiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1ODUyODMtNDhmMmEwNDAtNDQxNS00ZGE3LTkyNzktZGE1ZjNjNzc2MjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAwMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDBjYzc4MjY3NWNhZjIzNWQ4MjQ4OTUxYzM0ZTM5ZjlhYjNhNjBhOTIxZWY4NDJiNzhiZjM1Y2I4NmE4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94-xdg0nIc_3sVocTAUsil6TjTayFUCfZa7Fvz7Bb7c">
>
> docx가 지원이 안되네요!! 명시해주신 내용과 달라 코멘트 남깁니다!!
> 
> <img alt="image" width="1000" src="https://private-user-images.githubusercontent.com/63251068/328587943-7b6b27c1-0bcd-4c0a-b3df-0661022a0ff1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjcwMTIsIm5iZiI6MTcxNTEyNjcxMiwicGF0aCI6Ii82MzI1MTA2OC8zMjg1ODc5NDMtN2I2YjI3YzEtMGJjZC00YzBhLWIzZGYtMDY2MTAyMmEwZmYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAwMDUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZDM5MGEzMTlhOTU0NTk5MzgyZGQ1Y2I5MWNiY2EzNGM1M2NiMDQyODg0Yzk4ODNmOGMyYjlhYjQzODk4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6y316ahLf1WEk35KVdK9bDcx__6sRLgDQcLv8tvPIKg">
> 그리고 간단한 텍스트 한 줄만 나왔는데 굉장한 문제가 튀어나왔네요. 되게 좋은 것 같아요!! 다만 조금만 파일이 커져도 토큰 수 초과했다고 떠서 테스트 케이스 만드는 게 좀 어려웠습니다. 혹시 토큰 수 제한은 2500이 한계인가요?

- 피드백 감사합니다. docx 파일이 지원 안되는 오류 해결했습니다.
- chatgpt api 사용 비용을 줄이기 위해 토큰 수를 2,500으로 제한했습니다. 토큰 제한을 3000까지 올리겠습니다.
- 영어로 작성된 문서로 테스트하시면 텍스트 대비 토큰을 줄일 수 있습니다.
- 혹은 아래 사진과 같이 특정 페이지만을 분리하여 테스트하시는 것을 추천드립니다.

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/48846088/0b223df0-aa58-492e-95b6-e1c41c4f25fe)

**Comment by WickedFoxes** [comment]
# 2024-05-08 오전 10:00 DB 초기화
examgpt의 db가 초기화되는 오류가 발생했습니다.
db를 새로 생성하였으며, 기존에 테스트하셨던 계정과 문제 내용들이 모두 사라진 점 안내드립니다.
현재 db 백업 기능을 추가해두었으며
다음에 db가 초기화 될 시 백업된 db로 복구하도록 하겠습니다.

**Comment by euije** [comment]
안녕하세요~ 4조 이의제라고 합니다
프롬프트를 잘 연구하셨는지, 문제 퀄리티가 굉장한 것 같네요 👍👍👍👍
오픈소스 강의자료 1강으로 입력했는데, 질 좋은 문제를 많이 만들어주어서 복습을 잘할 수 있을 것 같아요 ㅎㅎ

가끔 아래와 같이 문제가 잘못나오는 경우도 있나봐요 ㅜㅜ 이건 GPT의 한계이겠죠?
다음 스프린트 때 이런 문제를 보완해도 좋을 것 같습니다!

<img width="1003" alt="스크린샷 2024-05-08 오후 7 35 25" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12531340/34501978-2c60-40a4-8b86-3b95ee86213c">

**Comment by yjyoo3312** [comment]
<img width="793" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/bbcb009b-edeb-4174-ae7a-dc342105afa4">
Computer Vision 수업 퀴즈로도 활용해 볼 수 있겠군요:) 제 예상보다 문제가 잘 만들어지네요

**Comment by Urchinode** [comment]
등록한 메모를 단위로 문제를 그룹화한 것에서 편의성이 좋다고 느꼈습니다! UI도 깔끔해서 좋아요~ 👍

개인적으로 아래의 기능이 있다면 사용자 경험과 문제의 질을 개선하는데 도움이 될 것 같습니다

- 메모 폴더에 **업로드한 파일명**도 같이 보여주기: 메모 폴더가 많이 생성됐을 때 쉽게 식별하기 위함
- **피드백 input**: `추천`, `삭제` 버튼 이외에 `피드백` 버튼을 추가해보는건 어떨까요? 사용자가 피드백 사유를 입력하도록 input 칸을 마련해두면 사용자 추가 요구사항이나 버그를 자세히 알아낼 수 있을 것 같습니다!

**Comment by sihumji00** [comment]
문제 퀄리티도 좋고 욕설이 포함된 텍스트 파일을 넣었을 때 모더레이션 시스템도 잘 구현된 것 같아요! 데모인데도 불구하고 퀄리티가 상당히 우수한 것 같습니다!

문제 밑에 정답을 바로 알려주는 것도 좋지만 사용자가 문제를 풀어본 후 정답을 확인할 수 있게 정답 부분을 한 번 클릭해서 볼 수 있도록 가려두거나 혹은 사용자가 정답을 입력하면 gpt가 채점해주면서 해설을 보여주는 등의 기능도 있으면 좋을 것 같아요!

**Comment by thdudgus** [comment]
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/84049315-44df-4b9a-aefb-2ac796c757f9)
객관식 문제로 생성하기를 눌렀는데, 선지가 안 나오고 선지 답 버튼만 출력되는 오류가 있는 것 같습니다!
pdf로 문제 생성했습니다.
자잘한 오류들이 고쳐지면 공부할 때 정말 유용할 것 같습니다 :)

**Comment by minseok128** [comment]
안녕하세요. 5조의 장민석입니다.

우선 깔끔한 UI와 완성도 높은 사용자 경험이 정말 인상적이었습니다!
특히 문제의 퀄리티가 높고, description으로 해설도 해주는 점이 좋았습니다.
> <img width="794" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/27052038/c00ed990-14e8-4ae4-9239-50f7282d1442">
다만 테스트에 적당한 pdf를 찾기 꽤나 어려웠는데, 아마 3000 토큰 제한이 생각보다 널널하지 않아서 그런 것 같았습니다.
pdf를 넣으면, 이를 1장씩 분리해서 생성하는 등의 방법으로 더 좋은 사용자 경험을 줄 수 있을 것 같아 의견 공유드립니다!
