### ISSUE TITLE
[DEMO 1][10조] Game Recommend GPT

### ISSUE THREAD

**Issue by randy0119** [PiLab-CAU/OpenSourceProject-2401#8]
# 데모 링크: http://4.217.249.244:3000
- 클라우드 환경에 배포되어있어 24시간 이용 가능합니다.
- 사용자 당 질의 횟수는 100회로 제한되어 있습니다.
# 사용 설명
## 1. Landing Page 접속
- 위의 주소로 접속하면 다음과 같은 메인 화면을 볼 수 있습니다.

![1](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/96b35983-e131-4639-9086-87b8c532abe2)

## 2. 취향이 드러나는 게임 추천 질의 입력
-` 학번`을 입력하고, 자신이 원하는 게임의 특징이 담긴 게임 추천 `사용자 질의`를 입력하고 `전송` 버튼을 누릅니다.
- **GPT 답변 생성까지 최장 30초 소요됩니다.**
- ex.` {"학번":12345678, "유저 쿼리":"배경이 아름답고 자유도 높기로 유명한 어드벤처 게임 추천해줘."}`

![2](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/4025102e-efe3-4501-8b5d-9b9fd3537ee3)

## 3. 추천 결과 조회 및 피드백 입력
- GPT로 생성된 추천 결과를 조회합니다.(24-05-07 [DEMO 1] 기준, RAG 미반영)
- 추천결과에 대한 `만족도`와 `피드백`을 입력하고 `제출하기` 버튼을 누릅니다.
- ex. 결과 만족 시, `{"만족도를 입력해주세요":"Good", "피드백":"의도가 잘 반영되었다. 다만 더 다양한 게임을 추천했으면 좋겠다."}`

![3](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/83d13533-cb92-4f51-9d63-7b873ed51871)

## 4. 마지막 추천 결과 다시 받기
- 다시 메인 화면으로 넘어와서, 같은 학번을 입력한 후,` "마지막 추천 결과 반환해줘"`와 같은 질의를 제출하면 **GPT가 마지막으로 추천 결과를 반환**합니다.

![4](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/62f3c916-bd5a-4d13-895e-9f9e409992d0)

## 5. 용도에 맞지 않는 질의
- 게임 추천 질의와 상관없는 질의 입력 시, 기능이 제한됩니다.

![5](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/76a661cf-1df2-49c5-9bf7-50f9c8cc9727)

## 6. bad word
- 폭언 및 유해 단어가 들어오면 기능이 제한됩니다.

![6](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/71533266/7c94ab22-29e0-41ee-8108-cbdec6d06112)

**Comment by yjyoo3312** [comment]
@randy0119 예 감사합니다. Readme의 이미지가 깨지는 거 같아서 확인 부탁드려요~

**Comment by randy0119** [comment]
> @randy0119 예 감사합니다. Readme의 이미지가 깨지는 거 같아서 확인 부탁드려요~

확인 감사드립니다. 새로운 사진 파일로 교체했습니다!

**Comment by Tastypotato245** [comment]
<img width="976" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/38878c0a-4c76-4a6b-9a97-15661bed8b83">

취향에 맞는 게임이 잘 추천되네요!! 재밌어요

한 번 질문 후 추가 질문하는 기능도 있으면 좋겠습니다! 저는 The Room과 Portal 모두 재미있게 했는데, 처음에

방탈출, 퀴즈 게임 추천해줘~ 라는 말에 처음부터 제가 한 게임들을 제외하고 추천해달라고 하기에는 작성해야하는 내용이 많기 때문입니다.

점진적으로

1. ~~장르 추천해줘
2. 아 나 그게임들은 해봤어 다른 게임들 추천해줘~

라는 식으로 여러 번 응답할 수 있게 하는 것도 좋아보여요!!

**Comment by bykbyk0401** [comment]
<img width="973" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/67e5cc3d-b5ab-4f82-82fd-e3a59260979f">

1. 피드백 후 '마지막 추천 결과 반환해줘' 입력 후 30초가 지나도 응답이 없다가 시간초과 오류가 났었는데, 다시 한번 입력하니까 아래와 같은 동일한 결과가 나와서 아쉬웠습니다. 추천 게임이 더 다양하거나, 더이상 해당 게임이 없을 때의 응답이 다르면 더 좋을 것 같다는 생각이 듭니다!!

![IMG_3066](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/102952855/40e7cd1e-bd86-4ffb-a631-581d85cf29b0)

2. 추가적으로, '마지막 추천 결과 반환해줘' 라는 문구가 작성되어있거나, 버튼을 누르면 자동으로 입력되어 넘어가도록 하면 더 편리할 것 같다는 생각이 듭니다.

++) 그리고 학번 전체자리를 다 입력해야한다는 점이 조금 부담이 될 수 있을것 같기도 합니다,,ㅎㅎㅎ
더 확장되었을 때에도 변경이 필요한 사항이라 생각되어, 다른 인증방식이 도입되면 더 좋지 않을까 생각됩니다!

아직 저에게 해당되는 재미있는 게임은 찾지 못해 아쉽지만, 앞으로의 개선 후 찾을 수 있으면 좋겠네요^^
수고하셨습니다~

**Comment by yjyoo3312** [comment]
<img width="968" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/e90b28ee-84b1-4be3-837c-0af03bae905e">
학번은 랜덤으로 입력해도 작동을 하는군요 (일단 랜덤으로 입력했습니다)

재밌게 했던 게임이 답변으로 나와서 좋네요

**Comment by randy0119** [comment]
@Tastypotato245 님! 데모 테스트에 참여해주셔서 감사합니다😄 

추천 결과에 만족하셨다니 다행입니다! 피드백 남겨주신 '추가 질문 기능', '장르 게임 추천 기능', '다른 게임 추천 기능' 사항들은 다음번 데모에 우선적으로 구현될 수 있게 신경쓰도록 하겠습니다. 다시 한 번 성심성의껏 남겨주신 피드백에 감사드립니다🤝

**Comment by randy0119** [comment]
@bykbyk0401 님! 우선 데모 테스트에 참여해주셔서 감사합니다😆

테스트 과정 중 불편을 드려서 송구스럽게 생각하고 있습니다...ㅠㅠ 현재는 기능 구현에 초점을 맞춘 초기 버전의 GPT Agent라 GPT 응답속도에 다소 편차가 있을 수 있습니다. 이러한 편차를 인지하고, 앞으로 개발 일정에서는 프롬프트 엔지니어링 등, 유저가 더욱 균일하고 빠른 결과를 받아볼 수 있도록 노력할 계획입니다!

더불어 염려하신 학번 전체 입력에 대해서는 서비스 정책에 관한 내부 논의를 거쳐서, 학번 부분 입력 혹은, 개인 수준이 아닌 팀 수준의 Identification 절차 적용 등 조금 더 개인정보 보호적인(?) 방법으로 전환하도록 하겠습니다.

마지막으로 추후 추천 기능의 향상에 관해서 이야기드리자면... 현재는 오직 GPT에 의지해서 게임추천을 진행하고 있습니다. 그러나 저희는 최종적으로 RAG 구조를 적용해 높은 정확도로 더욱 다양한 게임을 추천하는 것을 목표로 하고 있습니다! 진행상황을 맛보기로 알려드리자면, 5월 9일 기준, Steam 게임 플랫폼에 대한 크롤링을 통해 원천 게임정보를 수집했습니다. 해당 게임 정보를 임베딩 검색하는 기능을 이번달 내로 구현하고, 돌아오는 6월엔 Steam 게임에 대한 추천도 받으실 수 있도록 적용할 계획입니다.

상세한 피드백 감사드립니다! 부디 다음번엔 합리적인 추천 결과를 받으실 수 있도록 최선을 다하겠습니다🙏

**Comment by randy0119** [comment]
@yjyoo3312 님! 데모 테스트에 참여해주셔서 감사합니다!!!

실제로 경험하고 만족했던 게임을 추천 받으셨다는 이야기에 소소한 보람을 느낍니다...ㅎㅎㅎ
기대감을 조금 더 심어드리자면 이후에는 RAG를 통한 최신 게임 추천 기능 지원을 계획하고 있습니다.
다음번 유저 경험에는 "만족한 게임을 추천 받는 것" 뿐만 아니라, "만족할 게임을 추천 받도록" 저희가 더욱 노력하겠습니다!
다시 한 번 힘이 되는 피드백 감사드립니다😍

**Comment by kimseongsun** [comment]
[공지]
현재 사용자에 따라 서버가 제대로 작동하지 않는 현상이 발생되고 있습니다.
복구가 완료되면 안내 드리겠습니다

**Comment by kimseongsun** [comment]
### **[공지]**
현재 시각 05:01 점검을 위해 잠시 서버를 close하겠습니다
서버가 open되면 다시 공지 해드리겠습니다
불편을 드려 죄송합니다

**Comment by randy0119** [comment]
> ### **[공지]**
> 현재 시각 05:01 점검을 위해 잠시 서버를 close하겠습니다 서버가 open되면 다시 공지 해드리겠습니다 불편을 드려 죄송합니다

### [24-05-09 10:20]부로 서버 복구 완료했습니다.
원인 파악 후 재발 방지에 최선을 다하겠습니다.

**Comment by shu030929** [comment]
"흔하지 않은 공포게임 추천해줘" 처럼 모호한 질문을 던져도, 질문에 딱 맞는 게임들을 추천해줘서 좋아요!! 오늘 밤에 해봐야겠습니다

<img width="1025" alt="스크린샷 2024-05-09 오후 3 12 04" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/166142544/5e4b1161-b6b7-4809-b2b5-d255e38f9547">
"~와 같은 게임 추천해줘" 같은 질문을 했을때, 비슷한 유형의 게임을 추천해주기보단 게임을 분석 하더라구요.

그래서 적당한 피드백 제출 후 스팀에 있는 다른 게임에 대해 똑같은 질문을 했는데 작동이 잘 됩니다!
<img width="997" alt="스크린샷 2024-05-09 오후 3 28 18" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/166142544/26149181-f4af-4187-b02e-22c8c5176b18">

**Comment by Handoni** [comment]
전반적으로 잘 동작하고, 꽤 질 높은 추천을 해 주는 것 같습니다!
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/101948889/6707fb7e-2d55-40e0-a75d-ae39045ce0ab)
다만 위 사례와 같이, 좀 힐링되는 시뮬레이션 게임 종류에 좀비 아포칼립스를 추천해 주는 다소 카테고리 분류가 아쉬운 부분이 있었습니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/101948889/bf026798-2d99-4c82-9177-a4fb716dfed8)
또한 모바일게임이라고 지정해주니, (아마도) 실제로 없는 게임도 나오더라고요..!
추후 임베딩 할때 장르나 플랫폼 카테고리화가 좀 중요하고, 할루시네이션 제거도 중요해 보입니다!
전반적으로는 잘 되는 것 같습니다! 수고하셨습니다 😊

**Comment by seongsunkim** [comment]
@Handoni 님! 데모 테스트에 참여해 주셔서 감사합니다!

말씀 주신 피드백에 대해서 말씀드리자면, 
현재 크롤링을 통한 카테고리 Embedding, RAG 작업이 활발하게 작업 중이고,
Prompt 응답 생성 분야도 자체적인 evaluation Test를 이용해서 Hallucination과 Filtering 기능을 개선 중이므로
다음엔 데모 때에는 좀 더 정확한 서비스를 제공 받으실 수 있을 것이라 생각합니다!

꼭 다음번 데모도 이용해 주시면 감사하겠습니다 :)

**Comment by kimseongsun** [comment]
@shu030929 님! 데모 테스트에 참여해 주셔서 감사합니다!

마음에 드신 게임을 추천받으셔서 다행입니다 :) 
말씀 주신 피드백에 대해서 말씀드리자면, 
다음번 데모에는 응답이 생성되었을 때 비슷한 유형의 게임을 추천하는 서비스, 
응답 창에서 질문 쿼리를 다시 날릴 수 있는 창을 만드는 것을 계획하고 있습니다. 
꼭 다음번 데모도 이용해 주시면 감사하겠습니다
( _ _ )
마지막으로 너무 과도한 게임은 금물이니 추천 게임은 적당히 즐겨주세요 :)

**Comment by kimseongsun** [comment]
@Handoni 님! 데모 테스트에 참여해 주셔서 감사합니다!

말씀 주신 피드백에 대해서 말씀드리자면, 
현재 크롤링을 통한 카테고리 Embedding, RAG 작업이 활발하게 작업 중이고,
Prompt 응답 생성 분야도 자체적인 Evaluation Test를 이용해서 Hallucination과 Filtering 기능을 개선 중이므로
다음엔 데모 때에는 좀 더 정확한 서비스를 제공 받으실 수 있을 것이라 생각합니다!

꼭 다음번 데모도 이용해 주시면 감사하겠습니다 :)

**Comment by minseok128** [comment]
안녕하세요! 5조의 장민석입니다.

생각보다도 훨씬 추천을 잘 해줘서 놀랐습니다!

추후 DB를 연결하여 게임의 이미지, 링크등도 제공되면 훨씬 좋은 추천 서비스가 될 것 같습니다.

ps.
테스트 중간에 전송버튼을 2번 누르게 되었는데, 이에 대해 뭔가 비정상적인 동작을 하는 것 같습니다.
> <img width="682" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/27052038/fb163d3d-23cd-4d59-a6a1-5b1964e998e7">

**Comment by kimseongsun** [comment]
@minseok128 님! 데모 테스트에 참여해 주셔서 감사합니다!
우선 데모 서비스에 관한 칭찬 감사드립니다 :)

말씀주신 피드백에 관해서 생각을 해봤는데..
저희 쪽에서도 처음 보는 예외 동작이라서
DB쪽에서 사용자 로그를 통해서 원인 파악을 하고 개선시키겠습니다

좋은 피드백 감사드립니다 ( _ _ )
