### ISSUE TITLE
[demo1][6조] Apayo

### ISSUE THREAD

**Issue by thdudgus** [PiLab-CAU/OpenSourceProject-2401#9]
# 1-1. 데모 링크
https://apayo-d426b.web.app/ 
---
# 1-2. 사용 설명
### 데모 실행 방법 (웹 비율로 실행해주셔야 합니다.)
1. Login과 Sign UP 버튼이 있는 화면이 처음으로 보이게 되는데, 두 버튼 중 Login을 클릭합니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/f52b5339-5bde-47a0-8e15-af3bacf89ad7)

2. Log In 페이지로 이동하게 되는데, 정보를 입력하지 않은 상태로, Login 버튼을 클릭합니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/fe0e28b1-4442-4c1f-8222-64705a273c9d)

3. '증상을 입력하세요.'라고 쓰인 채팅 바에 증상을 입력한 후, 엔터를 누르거나 보내기 아이콘을 클릭하고, 추가 증상 질문 버튼이 나오기까지 일정 시간 기다립니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/be04664a-8b44-478d-bcfe-8825871d8281)

4. 사용자가 입력한 증상에 기반하여 추가 증상 질문 버튼들이 생성됩니다. 그 중 사용자가 겪고 있는 증상을 모두 클릭합니다. (질문의 개수가 많은 경우 스크롤 가능)
5. 모두 선택했으면 좌측 하단에 '진단 받아보기 >' 버튼을 클릭하고, 결과가 나올 때까지 일정시간 기다립니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/7dda42b8-6416-45df-b6b9-d044cde083e0)

=> 결과 : 가장 유력한 질병(증상)과 상세 설명, 그리고 추천 진료과가 출력됩니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/87588784/93dc0dcf-f464-4ce1-bb9c-ce1cf5241a55)

### 최종적으로 구현해야할 기능
- 사용자의 입력(채팅과 증상 선지 선택)을 기반으로 가장 유력한 질병(증상)과 상세 설명, 그리고 추천 진료과 출력.
- 추천 진료과를 사용자의 위치에 기반하여 검색하여 병원 여부와 관련 정보(전문의, 3차 병원 여부 등) 출력.
- 위 정보를 상시 열람 가능하도록 저장 및 목록화.
- 로그인, 회원가입, 개인별 특이 정보(지병, 임신 등) 관리. 입력.
- UI 상에서의 예외처리(사용자의 중복 입력 등 방지 처리)

### 위 기능들 중 현재(데모)까지 구현한 기능
가장 중요한 기능인 "사용자의 입력(채팅과 증상 선지 선택)을 기반으로 가장 유력한 질병(증상)과 상세 설명, 그리고 추천 진료과 출력."을 구현하였습니다.
아직 임베딩을 하지 않아 정확도가 떨어질 수 있습니다.

**Comment by Tastypotato245** [comment]
제가 육회 먹고 배탈나서 해봤는데 괜찮네요!!

아까 병원 갔다왔는데 병원에서는 식중독이랍니다 ㅠㅠ 프롬프트에도 육회먹고 배탈났다고 했는데, 아쉽게도 식중독 이야기는 없네용

![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/63251068/3acf9e0e-8be0-46d2-8122-90b9e6f3dbe2)

그래도 카드 형식으로 키워드를 추리고 정리하는 방식에서 많은 영감을 얻어 갑니다!! 저희 팀도 카드 형식을 사용하려고 했거든요!(1조)

고생 많으셨습니다!!

**Comment by WickedFoxes** [comment]
- 05-08 오전 11:22 기준 '추가 증상 질문 버튼'이 생성되지 않고 있습니다. 대략 5분 정도 기다려도 생성되지 않습니다.
질문 내용 : 손목이 아파요

**Comment by 1105nam** [comment]
- 05-08 오후 02:30 기준 진단 결과 안내가 이루어지고 있지 않습니다.
질문 내용 : 수면에 어려움이 있어요.
![Screenshot_20240508_143033_Samsung Internet](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/37164539/7425d036-0aaf-44f7-ba9c-e4fef67fcc5d)

**Comment by IamGroooooot** [comment]
위에 분과는 다르게 서버가 내려간 것 같아요.

## 콘솔 로그
<img width="400" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/cc4d373c-05ac-48fe-b62f-3d18d2d88c7b">

나중에 다시 시도해볼게요!

<img width="400" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/38830620/a952d40c-cd79-403a-b773-a3ae3079c0ff">

**Comment by yjyoo3312** [comment]
아직 서버가 작동하지 않는 모양이군요
<img width="948" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/9f033129-0f9f-4926-981b-7cc881daeccf">

있다 다시 시도해 보겠습니다

**Comment by Urchinode** [comment]
CORS 에러가 나타나는 것 같습니다~
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/77256188/e01f3401-2fa8-49d3-a0f6-e66067cead94)

서버가 [https://apayo-d426b.web.app](https://apayo-d426b.web.app/)를 Allow Origin으로 허용해주도록 면 해결될 것 같습니다!
UI가 되게 보기 좋다고 느껴서 기능도 기대되네요 👍

**Comment by Bowoon1216** [comment]
역시 아직 에러가 나네요 😢 
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/105543811/6bb0e57e-1e51-4d47-b921-dffb958ba4fa)
그래도 디자인이 깔끔하고 잘되어있네요! 💯 
추후에 오류가 해결되면 다시 테스트 해보고 싶습니다~~

**Comment by Handoni** [comment]
로그가 안남아있어서 서버가 왜 다운되었는지 모르겠네요 😢
현재 정상 작동하는거 확인했습니다!
오류 확인해주신 분들 감사합니다..!

**Comment by Handoni** [comment]
+ 현재 유해성 검사나 관련없는 입력 필터링 기능은 프롬프트에서 제외하였습니다..!
프롬프팅으로 집어넣으니깐 질병 관련도 필터링되는 문제가 있어서, 이부분 이후 추가하도록 하겠습니다.
테스트 시 질병과 관련있는 메세지 위주로 날려주시면 감사하겠습니다.

**Comment by yjyoo3312** [comment]
테스트 잘 되는 군요! 아래와 같이 테스트를 해봤는데 일반적인 증상은 잘 잡히는 것 같습니다.
추후에는 오른쪽과 같은 더 어려운 케이스에 대해서는 "판단이 어려우니, 오프라인으로 확인해 주세요" 와 같은 느낌의 메세지를 띄워주셔도 어떤가요?

<img width="902" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/12525981/0ea17b1e-0494-44ac-8756-9ed841912590">

**Comment by Handoni** [comment]
감사합니다! 다음 버전에서는 꼭 고려해서 개발하도록 하겠습니다.
저희도 지금 계속 테스트 해보고 있는데, 종종 gpt가 형식을 안지켜서 답변줘서 에러가 뜨는 경우도 있는 것 같습니다.
혹시 테스트 진행 안되는 경우 다른 테스트 케이스로 진행하시고, 해당 케이스 알려주시면 감사하겠습니다!

**Comment by Richardyun01** [comment]
테스트 해보는데 아이콘 이후로 로딩이 되고 있지 않습니다. 사용자 문제일수도 있나요?
![스크린샷 2024-05-09 152228](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/60737804/a08b0a2d-6198-4e76-b0d6-942622453ce1)

**Comment by Handoni** [comment]
위 경우 아직 반응형 웹이 완전히 구현되지 못해서, 모바일 환경이 아닌 웹 환경에서 충분한 사이즈의 창을 사용해주시면 해결될 것 같습니다. 불편드려 죄송합니다 🥲

**Comment by Richardyun01** [comment]
항목 제시 기능과 진단 기능 다 잘 되는 것 같습니다. 다만 진단을 받은 뒤 이전 항목 선택지로 돌아가는 기능도 있었으면 좋을 것 같네요.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/60737804/86462b39-b5fa-483b-8cb9-f49a685970af)

**Comment by Handoni** [comment]
감사합니다! 해당 기능 염두에 두고 개발중이니 다음 버전에는 꼭 포함하도록 하겠습니다 😊

**Comment by Handoni** [comment]
5/10 13:45에 서버 다운 확인되어서 재시작 했습니다.

**Comment by minseok128** [comment]
안녕하세요. 5조의 장민석입니다.

카드를 선택하는 방식으로 ui/ux를 설계하신 점이 굉장히 인상적이었습니다!

확실히 선택지가 있고, 그 중에서 고를 수 있다보니 증상을 완전히 말로 설명하는 것보다 편하게 느껴집니다.
이런 점이 지식인 등의 서비스에 증상을 호소하는 것보다 훨씬 빠르게 심리적인 안정을 주는 것 같습니다!

ps. 이런식으로 관련없는 2가지 키워드를 분리해서 각각 추천해주는 점이 인상적이에요!
> <img width="867" alt="image" src="https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/27052038/b026ea5f-3b89-45b3-9b27-56981da36117">

**Comment by Handoni** [comment]
> 안녕하세요. 5조의 장민석입니다.
> 
> 카드를 선택하는 방식으로 ui/ux를 설계하신 점이 굉장히 인상적이었습니다!
> 
> 확실히 선택지가 있고, 그 중에서 고를 수 있다보니 증상을 완전히 말로 설명하는 것보다 편하게 느껴집니다. 이런 점이 지식인 등의 서비스에 증상을 호소하는 것보다 훨씬 빠르게 심리적인 안정을 주는 것 같습니다!
> 
> ps. 이런식으로 관련없는 2가지 키워드를 분리해서 각각 추천해주는 점이 인상적이에요!
> 
> > <img alt="image" width="867" src="https://private-user-images.githubusercontent.com/27052038/329480004-b026ea5f-3b89-45b3-9b27-56981da36117.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjM0NjksIm5iZiI6MTcxNTMyMzE2OSwicGF0aCI6Ii8yNzA1MjAzOC8zMjk0ODAwMDQtYjAyNmVhNWYtM2I4OS00NWIzLTliMjctNTY5ODFkYTM2MTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MzkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMWZkMTVmMzMyMmYxYTZjYmVmOTA2MWQxZmE0NDU2ZjZiY2ExNGE2ODUwM2FlMmRmMTYwOTRlMzZlZDM4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.htKNYfGv_nhOeIFNMLdwzfqhzSTLENi6MKe2J72qAbI">

감사합니다! 다음 버전에선 더 발전된 서비스 만들어보겠습니다! 😊

**Comment by skwent77** [comment]
안녕하세요 9조 신재현입니다.
![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/46518769/d0b8b64a-bada-4047-9950-da24784084d7)

머리가 아프면 어디 가야하는지 상당히 궁금해서 입력을 해봤습니다.
근데 머리가 아프다는 입력과 관련해서 가슴이 두근거린다는 왜 증상으로 추천해줬는지 궁금하네요.
결론적으로, 신경과 가면 된다는 것 알 수 있어서 좋았습니다.

**Comment by Handoni** [comment]
> 안녕하세요 9조 신재현입니다.
> ![image](https://github.com/PiLab-CAU/OpenSourceProject-2401/assets/46518769/d0b8b64a-bada-4047-9950-da24784084d7)
> 
> 머리가 아프면 어디 가야하는지 상당히 궁금해서 입력을 해봤습니다.
> 근데 머리가 아프다는 입력과 관련해서 가슴이 두근거린다는 왜 증상으로 추천해줬는지 궁금하네요.
> 결론적으로, 신경과 가면 된다는 것 알 수 있어서 좋았습니다.
> 
> 

테스트 감사합니다! 로그를 보니 고혈압 관련 질문이었네요! 질병 관련 확증편향을 피하기 위해 1차 예측된 질병 정보는 제공되지 않는점 양해 부탁드립니다 😊 다음번 버전에는 더 발전시켜 보겠습니다. 감사합니다!
